import bpy


def setup_hoop(object_name='hoop'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'hoop radius'
    val_2.outputs[0].default_value = 211.0
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'hoop depth'
    val_3.outputs[0].default_value = 400
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'hoop'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 8
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = 'hoop rotate rotation'
    vec_5.vector = [1.5707963267948966, 0.0, 0.0]
    xform_4 = node_tree.nodes.new("GeometryNodeTransform")
    xform_4.location = (300, 0)
    xform_4.label = 'hoop rotate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_4.inputs["Geometry"])
    node_tree.links.new(vec_5.outputs["Vector"], xform_4.inputs["Rotation"])
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (600, 280)
    val_7.label = 'h_hoop radius'
    val_7.outputs[0].default_value = 208.0
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (600, 560)
    val_8.label = 'h_hoop depth'
    val_8.outputs[0].default_value = 450
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (600, 0)
    prim_6.label = 'h_hoop'
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 8
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (900, 280)
    vec_10.label = 'h_hoop rotate rotation'
    vec_10.vector = [1.5707963267948966, 0.0, 0.0]
    xform_9 = node_tree.nodes.new("GeometryNodeTransform")
    xform_9.location = (900, 0)
    xform_9.label = 'h_hoop rotate'
    node_tree.links.new(prim_6.outputs["Mesh"], xform_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], xform_9.inputs["Rotation"])
    bool_11 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_11.location = (1200, 0)
    bool_11.label = 'difference'
    bool_11.operation = "DIFFERENCE"
    bool_11.solver = "EXACT"
    node_tree.links.new(xform_4.outputs["Geometry"], bool_11.inputs[0])
    node_tree.links.new(xform_9.outputs["Geometry"], bool_11.inputs[1])
    out_12 = node_tree.nodes.new("NodeGroupOutput")
    out_12.location = (1500, 0)
    out_12.label = "output"
    node_tree.links.new(bool_11.outputs[0], out_12.inputs[0])

    return node_tree




def setup_front_cover_hoop(object_name='front_cover_hoop'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'cover radius'
    val_2.outputs[0].default_value = 220.0
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'cover depth'
    val_3.outputs[0].default_value = 40
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'cover'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 256
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = 'cover rotate rotation'
    vec_5.vector = [1.5707963267948966, 0.0, 0.0]
    xform_4 = node_tree.nodes.new("GeometryNodeTransform")
    xform_4.location = (300, 0)
    xform_4.label = 'cover rotate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_4.inputs["Geometry"])
    node_tree.links.new(vec_5.outputs["Vector"], xform_4.inputs["Rotation"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'cover rotate translate translation'
    vec_7.vector = [0, 190, 0]
    xform_6 = node_tree.nodes.new("GeometryNodeTransform")
    xform_6.location = (600, 0)
    xform_6.label = 'cover rotate translate'
    node_tree.links.new(xform_4.outputs["Geometry"], xform_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], xform_6.inputs["Translation"])
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (900, 280)
    val_9.label = 'h_cover_border radius'
    val_9.outputs[0].default_value = 180.0
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (900, 560)
    val_10.label = 'h_cover_border depth'
    val_10.outputs[0].default_value = 60
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (900, 0)
    prim_8.label = 'h_cover_border'
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 256
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1200, 280)
    vec_12.label = 'h_cover_border rotate rotation'
    vec_12.vector = [1.5707963267948966, 0.0, 0.0]
    xform_11 = node_tree.nodes.new("GeometryNodeTransform")
    xform_11.location = (1200, 0)
    xform_11.label = 'h_cover_border rotate'
    node_tree.links.new(prim_8.outputs["Mesh"], xform_11.inputs["Geometry"])
    node_tree.links.new(vec_12.outputs["Vector"], xform_11.inputs["Rotation"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (1500, 280)
    vec_14.label = 'h_cover_border rotate translate translation'
    vec_14.vector = [0, 190, 0]
    xform_13 = node_tree.nodes.new("GeometryNodeTransform")
    xform_13.location = (1500, 0)
    xform_13.label = 'h_cover_border rotate translate'
    node_tree.links.new(xform_11.outputs["Geometry"], xform_13.inputs["Geometry"])
    node_tree.links.new(vec_14.outputs["Vector"], xform_13.inputs["Translation"])
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (1800, 280)
    val_16.label = 'hoop radius'
    val_16.outputs[0].default_value = 211.0
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (1800, 560)
    val_17.label = 'hoop depth'
    val_17.outputs[0].default_value = 400
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_15.location = (1800, 0)
    prim_15.label = 'hoop'
    node_tree.links.new(val_16.outputs["Value"], prim_15.inputs["Radius"])
    node_tree.links.new(val_17.outputs["Value"], prim_15.inputs["Depth"])
    prim_15.inputs["Vertices"].default_value = 8
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (2100, 280)
    vec_19.label = 'hoop rotate rotation'
    vec_19.vector = [1.5707963267948966, 0.0, 0.0]
    xform_18 = node_tree.nodes.new("GeometryNodeTransform")
    xform_18.location = (2100, 0)
    xform_18.label = 'hoop rotate'
    node_tree.links.new(prim_15.outputs["Mesh"], xform_18.inputs["Geometry"])
    node_tree.links.new(vec_19.outputs["Vector"], xform_18.inputs["Rotation"])
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (2400, 280)
    val_21.label = 'h_hoop radius'
    val_21.outputs[0].default_value = 208.0
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (2400, 560)
    val_22.label = 'h_hoop depth'
    val_22.outputs[0].default_value = 450
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_20.location = (2400, 0)
    prim_20.label = 'h_hoop'
    node_tree.links.new(val_21.outputs["Value"], prim_20.inputs["Radius"])
    node_tree.links.new(val_22.outputs["Value"], prim_20.inputs["Depth"])
    prim_20.inputs["Vertices"].default_value = 8
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (2700, 280)
    vec_24.label = 'h_hoop rotate rotation'
    vec_24.vector = [1.5707963267948966, 0.0, 0.0]
    xform_23 = node_tree.nodes.new("GeometryNodeTransform")
    xform_23.location = (2700, 0)
    xform_23.label = 'h_hoop rotate'
    node_tree.links.new(prim_20.outputs["Mesh"], xform_23.inputs["Geometry"])
    node_tree.links.new(vec_24.outputs["Vector"], xform_23.inputs["Rotation"])
    bool_25 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_25.location = (3000, 0)
    bool_25.label = 'difference'
    bool_25.operation = "DIFFERENCE"
    bool_25.solver = "EXACT"
    node_tree.links.new(xform_18.outputs["Geometry"], bool_25.inputs[0])
    node_tree.links.new(xform_23.outputs["Geometry"], bool_25.inputs[1])
    bool_26 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_26.location = (3300, 0)
    bool_26.label = 'difference'
    bool_26.operation = "DIFFERENCE"
    bool_26.solver = "EXACT"
    node_tree.links.new(xform_6.outputs["Geometry"], bool_26.inputs[0])
    node_tree.links.new(xform_13.outputs["Geometry"], bool_26.inputs[1])
    node_tree.links.new(bool_25.outputs["Mesh"], bool_26.inputs[1])
    out_27 = node_tree.nodes.new("NodeGroupOutput")
    out_27.location = (3600, 0)
    out_27.label = "output"
    node_tree.links.new(bool_26.outputs[0], out_27.inputs[0])

    return node_tree




def setup_bottom_cover_hoop(object_name='bottom_cover_hoop'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'cover radius'
    val_2.outputs[0].default_value = 220.0
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'cover depth'
    val_3.outputs[0].default_value = 40
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'cover'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 256
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = 'cover rotate rotation'
    vec_5.vector = [1.5707963267948966, 0.0, 0.0]
    xform_4 = node_tree.nodes.new("GeometryNodeTransform")
    xform_4.location = (300, 0)
    xform_4.label = 'cover rotate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_4.inputs["Geometry"])
    node_tree.links.new(vec_5.outputs["Vector"], xform_4.inputs["Rotation"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'cover rotate translate translation'
    vec_7.vector = [0, -190, 0]
    xform_6 = node_tree.nodes.new("GeometryNodeTransform")
    xform_6.location = (600, 0)
    xform_6.label = 'cover rotate translate'
    node_tree.links.new(xform_4.outputs["Geometry"], xform_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], xform_6.inputs["Translation"])
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (900, 280)
    val_9.label = 'hoop radius'
    val_9.outputs[0].default_value = 211.0
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (900, 560)
    val_10.label = 'hoop depth'
    val_10.outputs[0].default_value = 400
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (900, 0)
    prim_8.label = 'hoop'
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 8
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (1200, 280)
    vec_12.label = 'hoop rotate rotation'
    vec_12.vector = [1.5707963267948966, 0.0, 0.0]
    xform_11 = node_tree.nodes.new("GeometryNodeTransform")
    xform_11.location = (1200, 0)
    xform_11.label = 'hoop rotate'
    node_tree.links.new(prim_8.outputs["Mesh"], xform_11.inputs["Geometry"])
    node_tree.links.new(vec_12.outputs["Vector"], xform_11.inputs["Rotation"])
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (1500, 280)
    val_14.label = 'h_hoop radius'
    val_14.outputs[0].default_value = 208.0
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (1500, 560)
    val_15.label = 'h_hoop depth'
    val_15.outputs[0].default_value = 450
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_13.location = (1500, 0)
    prim_13.label = 'h_hoop'
    node_tree.links.new(val_14.outputs["Value"], prim_13.inputs["Radius"])
    node_tree.links.new(val_15.outputs["Value"], prim_13.inputs["Depth"])
    prim_13.inputs["Vertices"].default_value = 8
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (1800, 280)
    vec_17.label = 'h_hoop rotate rotation'
    vec_17.vector = [1.5707963267948966, 0.0, 0.0]
    xform_16 = node_tree.nodes.new("GeometryNodeTransform")
    xform_16.location = (1800, 0)
    xform_16.label = 'h_hoop rotate'
    node_tree.links.new(prim_13.outputs["Mesh"], xform_16.inputs["Geometry"])
    node_tree.links.new(vec_17.outputs["Vector"], xform_16.inputs["Rotation"])
    bool_18 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_18.location = (2100, 0)
    bool_18.label = 'difference'
    bool_18.operation = "DIFFERENCE"
    bool_18.solver = "EXACT"
    node_tree.links.new(xform_11.outputs["Geometry"], bool_18.inputs[0])
    node_tree.links.new(xform_16.outputs["Geometry"], bool_18.inputs[1])
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (2400, 280)
    val_20.label = 'h_cover_border radius'
    val_20.outputs[0].default_value = 180.0
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (2400, 560)
    val_21.label = 'h_cover_border depth'
    val_21.outputs[0].default_value = 60
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_19.location = (2400, 0)
    prim_19.label = 'h_cover_border'
    node_tree.links.new(val_20.outputs["Value"], prim_19.inputs["Radius"])
    node_tree.links.new(val_21.outputs["Value"], prim_19.inputs["Depth"])
    prim_19.inputs["Vertices"].default_value = 256
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (2700, 280)
    vec_23.label = 'h_cover_border rotate rotation'
    vec_23.vector = [1.5707963267948966, 0.0, 0.0]
    xform_22 = node_tree.nodes.new("GeometryNodeTransform")
    xform_22.location = (2700, 0)
    xform_22.label = 'h_cover_border rotate'
    node_tree.links.new(prim_19.outputs["Mesh"], xform_22.inputs["Geometry"])
    node_tree.links.new(vec_23.outputs["Vector"], xform_22.inputs["Rotation"])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (3000, 280)
    vec_25.label = 'h_cover_border rotate translate translation'
    vec_25.vector = [0, -170, 0]
    xform_24 = node_tree.nodes.new("GeometryNodeTransform")
    xform_24.location = (3000, 0)
    xform_24.label = 'h_cover_border rotate translate'
    node_tree.links.new(xform_22.outputs["Geometry"], xform_24.inputs["Geometry"])
    node_tree.links.new(vec_25.outputs["Vector"], xform_24.inputs["Translation"])
    bool_26 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_26.location = (3300, 0)
    bool_26.label = 'difference'
    bool_26.operation = "DIFFERENCE"
    bool_26.solver = "EXACT"
    node_tree.links.new(xform_6.outputs["Geometry"], bool_26.inputs[0])
    node_tree.links.new(bool_18.outputs["Mesh"], bool_26.inputs[1])
    node_tree.links.new(xform_24.outputs["Geometry"], bool_26.inputs[1])
    out_27 = node_tree.nodes.new("NodeGroupOutput")
    out_27.location = (3600, 0)
    out_27.label = "output"
    node_tree.links.new(bool_26.outputs[0], out_27.inputs[0])

    return node_tree




def setup_roll_track(object_name='roll_track'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'cover radius'
    val_2.outputs[0].default_value = 220.0
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (0, 560)
    val_3.label = 'cover depth'
    val_3.outputs[0].default_value = 50
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 0)
    prim_1.label = 'cover'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 256
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (300, 280)
    vec_5.label = 'cover rotate rotation'
    vec_5.vector = [1.5707963267948966, 0.0, 0.0]
    xform_4 = node_tree.nodes.new("GeometryNodeTransform")
    xform_4.location = (300, 0)
    xform_4.label = 'cover rotate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_4.inputs["Geometry"])
    node_tree.links.new(vec_5.outputs["Vector"], xform_4.inputs["Rotation"])
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (600, 280)
    val_7.label = 'hoop radius'
    val_7.outputs[0].default_value = 211.0
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (600, 560)
    val_8.label = 'hoop depth'
    val_8.outputs[0].default_value = 400
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (600, 0)
    prim_6.label = 'hoop'
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 8
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (900, 280)
    vec_10.label = 'hoop rotate rotation'
    vec_10.vector = [1.5707963267948966, 0.0, 0.0]
    xform_9 = node_tree.nodes.new("GeometryNodeTransform")
    xform_9.location = (900, 0)
    xform_9.label = 'hoop rotate'
    node_tree.links.new(prim_6.outputs["Mesh"], xform_9.inputs["Geometry"])
    node_tree.links.new(vec_10.outputs["Vector"], xform_9.inputs["Rotation"])
    bool_11 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_11.location = (1200, 0)
    bool_11.label = 'difference'
    bool_11.operation = "DIFFERENCE"
    bool_11.solver = "EXACT"
    node_tree.links.new(xform_4.outputs["Geometry"], bool_11.inputs[0])
    node_tree.links.new(xform_9.outputs["Geometry"], bool_11.inputs[1])
    val_13 = node_tree.nodes.new("ShaderNodeValue")
    val_13.location = (1500, 280)
    val_13.label = 'h_external radius'
    val_13.outputs[0].default_value = 222.0
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (1500, 560)
    val_14.label = 'h_external depth'
    val_14.outputs[0].default_value = 30
    prim_12 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_12.location = (1500, 0)
    prim_12.label = 'h_external'
    node_tree.links.new(val_13.outputs["Value"], prim_12.inputs["Radius"])
    node_tree.links.new(val_14.outputs["Value"], prim_12.inputs["Depth"])
    prim_12.inputs["Vertices"].default_value = 256
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (1800, 280)
    vec_16.label = 'h_external rotate rotation'
    vec_16.vector = [1.5707963267948966, 0.0, 0.0]
    xform_15 = node_tree.nodes.new("GeometryNodeTransform")
    xform_15.location = (1800, 0)
    xform_15.label = 'h_external rotate'
    node_tree.links.new(prim_12.outputs["Mesh"], xform_15.inputs["Geometry"])
    node_tree.links.new(vec_16.outputs["Vector"], xform_15.inputs["Rotation"])
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (2100, 280)
    val_18.label = 'h_external radius'
    val_18.outputs[0].default_value = 212.5
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (2100, 560)
    val_19.label = 'h_external depth'
    val_19.outputs[0].default_value = 30.125
    prim_17 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_17.location = (2100, 0)
    prim_17.label = 'h_external'
    node_tree.links.new(val_18.outputs["Value"], prim_17.inputs["Radius"])
    node_tree.links.new(val_19.outputs["Value"], prim_17.inputs["Depth"])
    prim_17.inputs["Vertices"].default_value = 256
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (2400, 280)
    vec_21.label = 'h_external rotate rotation'
    vec_21.vector = [1.5707963267948966, 0.0, 0.0]
    xform_20 = node_tree.nodes.new("GeometryNodeTransform")
    xform_20.location = (2400, 0)
    xform_20.label = 'h_external rotate'
    node_tree.links.new(prim_17.outputs["Mesh"], xform_20.inputs["Geometry"])
    node_tree.links.new(vec_21.outputs["Vector"], xform_20.inputs["Rotation"])
    bool_22 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_22.location = (2700, 0)
    bool_22.label = 'difference'
    bool_22.operation = "DIFFERENCE"
    bool_22.solver = "EXACT"
    node_tree.links.new(xform_15.outputs["Geometry"], bool_22.inputs[0])
    node_tree.links.new(xform_20.outputs["Geometry"], bool_22.inputs[1])
    bool_23 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_23.location = (3000, 0)
    bool_23.label = 'difference'
    bool_23.operation = "DIFFERENCE"
    bool_23.solver = "EXACT"
    node_tree.links.new(bool_11.outputs["Mesh"], bool_23.inputs[0])
    node_tree.links.new(bool_22.outputs["Mesh"], bool_23.inputs[1])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (3300, 280)
    vec_25.label = 'difference translate translation'
    vec_25.vector = [0, 145, 0]
    xform_24 = node_tree.nodes.new("GeometryNodeTransform")
    xform_24.location = (3300, 0)
    xform_24.label = 'difference translate'
    node_tree.links.new(bool_23.outputs["Mesh"], xform_24.inputs["Geometry"])
    node_tree.links.new(vec_25.outputs["Vector"], xform_24.inputs["Translation"])
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (3600, 280)
    val_27.label = 'cover radius'
    val_27.outputs[0].default_value = 220.0
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (3600, 560)
    val_28.label = 'cover depth'
    val_28.outputs[0].default_value = 50
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (3600, 0)
    prim_26.label = 'cover'
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 256
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (3900, 280)
    vec_30.label = 'cover rotate rotation'
    vec_30.vector = [1.5707963267948966, 0.0, 0.0]
    xform_29 = node_tree.nodes.new("GeometryNodeTransform")
    xform_29.location = (3900, 0)
    xform_29.label = 'cover rotate'
    node_tree.links.new(prim_26.outputs["Mesh"], xform_29.inputs["Geometry"])
    node_tree.links.new(vec_30.outputs["Vector"], xform_29.inputs["Rotation"])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (4200, 280)
    val_32.label = 'hoop radius'
    val_32.outputs[0].default_value = 211.0
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (4200, 560)
    val_33.label = 'hoop depth'
    val_33.outputs[0].default_value = 400
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (4200, 0)
    prim_31.label = 'hoop'
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 8
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (4500, 280)
    vec_35.label = 'hoop rotate rotation'
    vec_35.vector = [1.5707963267948966, 0.0, 0.0]
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (4500, 0)
    xform_34.label = 'hoop rotate'
    node_tree.links.new(prim_31.outputs["Mesh"], xform_34.inputs["Geometry"])
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Rotation"])
    bool_36 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_36.location = (4800, 0)
    bool_36.label = 'difference'
    bool_36.operation = "DIFFERENCE"
    bool_36.solver = "EXACT"
    node_tree.links.new(xform_29.outputs["Geometry"], bool_36.inputs[0])
    node_tree.links.new(xform_34.outputs["Geometry"], bool_36.inputs[1])
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (5100, 280)
    val_38.label = 'h_external radius'
    val_38.outputs[0].default_value = 222.0
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (5100, 560)
    val_39.label = 'h_external depth'
    val_39.outputs[0].default_value = 30
    prim_37 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_37.location = (5100, 0)
    prim_37.label = 'h_external'
    node_tree.links.new(val_38.outputs["Value"], prim_37.inputs["Radius"])
    node_tree.links.new(val_39.outputs["Value"], prim_37.inputs["Depth"])
    prim_37.inputs["Vertices"].default_value = 256
    vec_41 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_41.location = (5400, 280)
    vec_41.label = 'h_external rotate rotation'
    vec_41.vector = [1.5707963267948966, 0.0, 0.0]
    xform_40 = node_tree.nodes.new("GeometryNodeTransform")
    xform_40.location = (5400, 0)
    xform_40.label = 'h_external rotate'
    node_tree.links.new(prim_37.outputs["Mesh"], xform_40.inputs["Geometry"])
    node_tree.links.new(vec_41.outputs["Vector"], xform_40.inputs["Rotation"])
    val_43 = node_tree.nodes.new("ShaderNodeValue")
    val_43.location = (5700, 280)
    val_43.label = 'h_external radius'
    val_43.outputs[0].default_value = 212.5
    val_44 = node_tree.nodes.new("ShaderNodeValue")
    val_44.location = (5700, 560)
    val_44.label = 'h_external depth'
    val_44.outputs[0].default_value = 30.125
    prim_42 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_42.location = (5700, 0)
    prim_42.label = 'h_external'
    node_tree.links.new(val_43.outputs["Value"], prim_42.inputs["Radius"])
    node_tree.links.new(val_44.outputs["Value"], prim_42.inputs["Depth"])
    prim_42.inputs["Vertices"].default_value = 256
    vec_46 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_46.location = (6000, 280)
    vec_46.label = 'h_external rotate rotation'
    vec_46.vector = [1.5707963267948966, 0.0, 0.0]
    xform_45 = node_tree.nodes.new("GeometryNodeTransform")
    xform_45.location = (6000, 0)
    xform_45.label = 'h_external rotate'
    node_tree.links.new(prim_42.outputs["Mesh"], xform_45.inputs["Geometry"])
    node_tree.links.new(vec_46.outputs["Vector"], xform_45.inputs["Rotation"])
    bool_47 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_47.location = (6300, 0)
    bool_47.label = 'difference'
    bool_47.operation = "DIFFERENCE"
    bool_47.solver = "EXACT"
    node_tree.links.new(xform_40.outputs["Geometry"], bool_47.inputs[0])
    node_tree.links.new(xform_45.outputs["Geometry"], bool_47.inputs[1])
    bool_48 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_48.location = (6600, 0)
    bool_48.label = 'difference'
    bool_48.operation = "DIFFERENCE"
    bool_48.solver = "EXACT"
    node_tree.links.new(bool_36.outputs["Mesh"], bool_48.inputs[0])
    node_tree.links.new(bool_47.outputs["Mesh"], bool_48.inputs[1])
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (6900, 280)
    vec_50.label = 'difference translate translation'
    vec_50.vector = [0, -145, 0]
    xform_49 = node_tree.nodes.new("GeometryNodeTransform")
    xform_49.location = (6900, 0)
    xform_49.label = 'difference translate'
    node_tree.links.new(bool_48.outputs["Mesh"], xform_49.inputs["Geometry"])
    node_tree.links.new(vec_50.outputs["Vector"], xform_49.inputs["Translation"])
    join_51 = node_tree.nodes.new("GeometryNodeJoinGeometry")
    join_51.location = (7200, 0)
    join_51.label = 'join'
    node_tree.links.new(xform_24.outputs["Geometry"], join_51.inputs["Geometry"])
    node_tree.links.new(xform_49.outputs["Geometry"], join_51.inputs["Geometry"])
    out_52 = node_tree.nodes.new("NodeGroupOutput")
    out_52.location = (7500, 0)
    out_52.label = "output"
    node_tree.links.new(join_51.outputs[0], out_52.inputs[0])

    return node_tree




def setup_chest(object_name='chest'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "chest size"
    vec_2.vector = [330, 420, 140]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'chest'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (300, 280)
    vec_4.label = 'chest translate translation'
    vec_4.vector = [0, 0, -320]
    xform_3 = node_tree.nodes.new("GeometryNodeTransform")
    xform_3.location = (300, 0)
    xform_3.label = 'chest translate'
    node_tree.links.new(prim_1.outputs["Mesh"], xform_3.inputs["Geometry"])
    node_tree.links.new(vec_4.outputs["Vector"], xform_3.inputs["Translation"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (600, 280)
    vec_6.label = "h_chest size"
    vec_6.vector = [300, 420, 110]
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (600, 0)
    prim_5.label = 'h_chest'
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (900, 280)
    vec_8.label = 'h_chest translate translation'
    vec_8.vector = [0, 10, -320]
    xform_7 = node_tree.nodes.new("GeometryNodeTransform")
    xform_7.location = (900, 0)
    xform_7.label = 'h_chest translate'
    node_tree.links.new(prim_5.outputs["Mesh"], xform_7.inputs["Geometry"])
    node_tree.links.new(vec_8.outputs["Vector"], xform_7.inputs["Translation"])
    bool_9 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_9.location = (1200, 0)
    bool_9.label = 'difference'
    bool_9.operation = "DIFFERENCE"
    bool_9.solver = "EXACT"
    node_tree.links.new(xform_3.outputs["Geometry"], bool_9.inputs[0])
    node_tree.links.new(xform_7.outputs["Geometry"], bool_9.inputs[1])
    out_10 = node_tree.nodes.new("NodeGroupOutput")
    out_10.location = (1500, 0)
    out_10.label = "output"
    node_tree.links.new(bool_9.outputs[0], out_10.inputs[0])

    return node_tree





# Execute all parts
setup_hoop()
setup_front_cover_hoop()
setup_bottom_cover_hoop()
setup_roll_track()
setup_chest()
