import bpy


def setup_dodecahedron_mesh_analysis(object_name='dodecahedron_mesh_analysis'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (0, 280)
    val_2.label = 'dodeca_seed radius'
    val_2.outputs[0].default_value = 2.0
    prim_1 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_1.location = (0, 0)
    prim_1.label = 'dodeca_seed'
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    prim_1.inputs["Subdivisions"].default_value = 1
    geom_op_3 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_3.location = (300, 0)
    geom_op_3.label = 'dodeca_seed dual'
    geom_op_3.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_1.outputs["Mesh"], geom_op_3.inputs["Mesh"])
    geom_op_4 = node_tree.nodes.new("GeometryNodeMeshToCurve")
    geom_op_4.location = (600, 0)
    geom_op_4.label = 'dodeca_seed dual edges'
    node_tree.links.new(geom_op_3.outputs["Dual Mesh"], geom_op_4.inputs["Mesh"])
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (900, 280)
    val_6.label = 'dodeca_seed radius'
    val_6.outputs[0].default_value = 2.0
    prim_5 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_5.location = (900, 0)
    prim_5.label = 'dodeca_seed'
    node_tree.links.new(val_6.outputs["Value"], prim_5.inputs["Radius"])
    prim_5.inputs["Subdivisions"].default_value = 1
    geom_op_7 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_7.location = (1200, 0)
    geom_op_7.label = 'dodeca_seed dual'
    geom_op_7.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_5.outputs["Mesh"], geom_op_7.inputs["Mesh"])
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (1500, 280)
    val_9.label = 'dodeca_seed radius'
    val_9.outputs[0].default_value = 2.0
    prim_8 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_8.location = (1500, 0)
    prim_8.label = 'dodeca_seed'
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    prim_8.inputs["Subdivisions"].default_value = 1
    geom_op_10 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_10.location = (1800, 0)
    geom_op_10.label = 'dodeca_seed dual'
    geom_op_10.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_8.outputs["Mesh"], geom_op_10.inputs["Mesh"])
    field_11 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_11.location = (2100, 0)
    field_11.label = 'index'
    geom_op_12 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_12.location = (2400, 0)
    geom_op_12.label = 'edge_angle_arms_edge_id'
    geom_op_12.domain = "EDGE"
    geom_op_12.data_type = "INT"
    geom_op_12.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_10.outputs["Dual Mesh"], geom_op_12.inputs["Geometry"])
    node_tree.links.new(field_11.outputs["Index"], geom_op_12.inputs["Value"])
    field_13 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_13.location = (2700, 0)
    field_13.label = 'edge_vertices'
    field_14 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_14.location = (3000, 0)
    field_14.label = 'edge_vertices'
    field_15 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_15.location = (3300, 0)
    field_15.label = 'edge_vertices'
    math_16 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_16.location = (3600, 0)
    math_16.label = 'vec_subtract'
    math_16.operation = "SUBTRACT"
    node_tree.links.new(field_14.outputs["Position 2"], math_16.inputs["Vector"])
    node_tree.links.new(field_15.outputs["Position 1"], math_16.inputs["Vector_001"])
    math_17 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_17.location = (3900, 0)
    math_17.label = 'vec_normalize'
    math_17.operation = "NORMALIZE"
    node_tree.links.new(math_16.outputs["Vector"], math_17.inputs["Vector"])
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (3900, 280)
    val_18.label = 'arm_length'
    val_18.outputs[0].default_value = 0.3
    math_19 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_19.location = (4200, 0)
    math_19.label = 'vec_scale'
    math_19.operation = "SCALE"
    node_tree.links.new(math_17.outputs["Vector"], math_19.inputs["Vector"])
    node_tree.links.new(val_18.outputs["Value"], math_19.inputs["Scale"])
    math_20 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_20.location = (4500, 0)
    math_20.label = 'vec_add'
    math_20.operation = "ADD"
    node_tree.links.new(field_13.outputs["Position 1"], math_20.inputs["Vector"])
    node_tree.links.new(math_19.outputs["Vector"], math_20.inputs["Vector_001"])
    geom_op_21 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_21.location = (4800, 0)
    geom_op_21.label = 'edge_angle_arms_pt_0'
    geom_op_21.mode = "EDGES"
    node_tree.links.new(geom_op_12.outputs["Geometry"], geom_op_21.inputs["Mesh"])
    node_tree.links.new(math_20.outputs["Vector"], geom_op_21.inputs["Position"])
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (4800, 280)
    val_22.label = 'edge_angle_arms_order_0'
    val_22.outputs[0].default_value = 0.0
    geom_op_23 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_23.location = (5100, 0)
    geom_op_23.label = 'edge_angle_arms_store_order_0'
    geom_op_23.domain = "POINT"
    geom_op_23.data_type = "FLOAT"
    geom_op_23.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_21.outputs["Points"], geom_op_23.inputs["Geometry"])
    node_tree.links.new(val_22.outputs["Value"], geom_op_23.inputs["Value"])
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (5400, 280)
    val_25.label = 'dodeca_seed radius'
    val_25.outputs[0].default_value = 2.0
    prim_24 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_24.location = (5400, 0)
    prim_24.label = 'dodeca_seed'
    node_tree.links.new(val_25.outputs["Value"], prim_24.inputs["Radius"])
    prim_24.inputs["Subdivisions"].default_value = 1
    geom_op_26 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_26.location = (5700, 0)
    geom_op_26.label = 'dodeca_seed dual'
    geom_op_26.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_24.outputs["Mesh"], geom_op_26.inputs["Mesh"])
    field_27 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_27.location = (6000, 0)
    field_27.label = 'index'
    geom_op_28 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_28.location = (6300, 0)
    geom_op_28.label = 'edge_angle_arms_edge_id'
    geom_op_28.domain = "EDGE"
    geom_op_28.data_type = "INT"
    geom_op_28.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_26.outputs["Dual Mesh"], geom_op_28.inputs["Geometry"])
    node_tree.links.new(field_27.outputs["Index"], geom_op_28.inputs["Value"])
    field_29 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_29.location = (6600, 0)
    field_29.label = 'edge_vertices'
    field_30 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_30.location = (6900, 0)
    field_30.label = 'edge_vertices'
    math_31 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_31.location = (7200, 0)
    math_31.label = 'vec_add'
    math_31.operation = "ADD"
    node_tree.links.new(field_29.outputs["Position 1"], math_31.inputs["Vector"])
    node_tree.links.new(field_30.outputs["Position 2"], math_31.inputs["Vector_001"])
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (7200, 280)
    val_32.label = 'half'
    val_32.outputs[0].default_value = 0.5
    math_33 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_33.location = (7500, 0)
    math_33.label = 'vec_scale'
    math_33.operation = "SCALE"
    node_tree.links.new(math_31.outputs["Vector"], math_33.inputs["Vector"])
    node_tree.links.new(val_32.outputs["Value"], math_33.inputs["Scale"])
    geom_op_34 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_34.location = (7800, 0)
    geom_op_34.label = 'edge_angle_arms_pt_1'
    geom_op_34.mode = "EDGES"
    node_tree.links.new(geom_op_28.outputs["Geometry"], geom_op_34.inputs["Mesh"])
    node_tree.links.new(math_33.outputs["Vector"], geom_op_34.inputs["Position"])
    val_35 = node_tree.nodes.new("ShaderNodeValue")
    val_35.location = (7800, 280)
    val_35.label = 'edge_angle_arms_order_1'
    val_35.outputs[0].default_value = 1.0
    geom_op_36 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_36.location = (8100, 0)
    geom_op_36.label = 'edge_angle_arms_store_order_1'
    geom_op_36.domain = "POINT"
    geom_op_36.data_type = "FLOAT"
    geom_op_36.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_34.outputs["Points"], geom_op_36.inputs["Geometry"])
    node_tree.links.new(val_35.outputs["Value"], geom_op_36.inputs["Value"])
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (8400, 280)
    val_38.label = 'dodeca_seed radius'
    val_38.outputs[0].default_value = 2.0
    prim_37 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_37.location = (8400, 0)
    prim_37.label = 'dodeca_seed'
    node_tree.links.new(val_38.outputs["Value"], prim_37.inputs["Radius"])
    prim_37.inputs["Subdivisions"].default_value = 1
    geom_op_39 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_39.location = (8700, 0)
    geom_op_39.label = 'dodeca_seed dual'
    geom_op_39.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_37.outputs["Mesh"], geom_op_39.inputs["Mesh"])
    field_40 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_40.location = (9000, 0)
    field_40.label = 'index'
    geom_op_41 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_41.location = (9300, 0)
    geom_op_41.label = 'edge_angle_arms_edge_id'
    geom_op_41.domain = "EDGE"
    geom_op_41.data_type = "INT"
    geom_op_41.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_39.outputs["Dual Mesh"], geom_op_41.inputs["Geometry"])
    node_tree.links.new(field_40.outputs["Index"], geom_op_41.inputs["Value"])
    field_42 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_42.location = (9600, 0)
    field_42.label = 'edge_vertices'
    field_43 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_43.location = (9900, 0)
    field_43.label = 'edge_vertices'
    field_44 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_44.location = (10200, 0)
    field_44.label = 'edge_vertices'
    math_45 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_45.location = (10500, 0)
    math_45.label = 'vec_subtract'
    math_45.operation = "SUBTRACT"
    node_tree.links.new(field_43.outputs["Position 1"], math_45.inputs["Vector"])
    node_tree.links.new(field_44.outputs["Position 2"], math_45.inputs["Vector_001"])
    math_46 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_46.location = (10800, 0)
    math_46.label = 'vec_normalize'
    math_46.operation = "NORMALIZE"
    node_tree.links.new(math_45.outputs["Vector"], math_46.inputs["Vector"])
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (10800, 280)
    val_47.label = 'arm_length'
    val_47.outputs[0].default_value = 0.3
    math_48 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_48.location = (11100, 0)
    math_48.label = 'vec_scale'
    math_48.operation = "SCALE"
    node_tree.links.new(math_46.outputs["Vector"], math_48.inputs["Vector"])
    node_tree.links.new(val_47.outputs["Value"], math_48.inputs["Scale"])
    math_49 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_49.location = (11400, 0)
    math_49.label = 'vec_add'
    math_49.operation = "ADD"
    node_tree.links.new(field_42.outputs["Position 2"], math_49.inputs["Vector"])
    node_tree.links.new(math_48.outputs["Vector"], math_49.inputs["Vector_001"])
    geom_op_50 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_50.location = (11700, 0)
    geom_op_50.label = 'edge_angle_arms_pt_2'
    geom_op_50.mode = "EDGES"
    node_tree.links.new(geom_op_41.outputs["Geometry"], geom_op_50.inputs["Mesh"])
    node_tree.links.new(math_49.outputs["Vector"], geom_op_50.inputs["Position"])
    val_51 = node_tree.nodes.new("ShaderNodeValue")
    val_51.location = (11700, 280)
    val_51.label = 'edge_angle_arms_order_2'
    val_51.outputs[0].default_value = 2.0
    geom_op_52 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_52.location = (12000, 0)
    geom_op_52.label = 'edge_angle_arms_store_order_2'
    geom_op_52.domain = "POINT"
    geom_op_52.data_type = "FLOAT"
    geom_op_52.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_50.outputs["Points"], geom_op_52.inputs["Geometry"])
    node_tree.links.new(val_51.outputs["Value"], geom_op_52.inputs["Value"])
    join_53 = node_tree.nodes.new("GeometryNodeJoinGeometry")
    join_53.location = (12300, 0)
    join_53.label = 'edge_angle_arms_points'
    node_tree.links.new(geom_op_23.outputs["Geometry"], join_53.inputs["Geometry"])
    node_tree.links.new(geom_op_36.outputs["Geometry"], join_53.inputs["Geometry"])
    node_tree.links.new(geom_op_52.outputs["Geometry"], join_53.inputs["Geometry"])
    field_54 = node_tree.nodes.new("GeometryNodeInputNamedAttribute")
    field_54.location = (12600, 0)
    field_54.label = 'attr:_edge_id'
    field_54.data_type = "INT"
    field_54.inputs["Name"].default_value = "_edge_id"
    field_55 = node_tree.nodes.new("GeometryNodeInputNamedAttribute")
    field_55.location = (12900, 0)
    field_55.label = 'attr:_point_order'
    field_55.data_type = "FLOAT"
    field_55.inputs["Name"].default_value = "_point_order"
    geom_op_56 = node_tree.nodes.new("GeometryNodePointsToCurves")
    geom_op_56.location = (13200, 0)
    geom_op_56.label = 'edge_angle_arms'
    node_tree.links.new(join_53.outputs["Geometry"], geom_op_56.inputs["Points"])
    node_tree.links.new(field_54.outputs["Attribute"], geom_op_56.inputs["Curve Group ID"])
    node_tree.links.new(field_55.outputs["Attribute"], geom_op_56.inputs["Weight"])
    val_58 = node_tree.nodes.new("ShaderNodeValue")
    val_58.location = (13500, 280)
    val_58.label = 'dodeca_seed radius'
    val_58.outputs[0].default_value = 2.0
    prim_57 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_57.location = (13500, 0)
    prim_57.label = 'dodeca_seed'
    node_tree.links.new(val_58.outputs["Value"], prim_57.inputs["Radius"])
    prim_57.inputs["Subdivisions"].default_value = 1
    geom_op_59 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_59.location = (13800, 0)
    geom_op_59.label = 'dodeca_seed dual'
    geom_op_59.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_57.outputs["Mesh"], geom_op_59.inputs["Mesh"])
    field_60 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_60.location = (14100, 0)
    field_60.label = 'index'
    geom_op_61 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_61.location = (14400, 0)
    geom_op_61.label = 'flat_edge_connectors_edge_id'
    geom_op_61.domain = "EDGE"
    geom_op_61.data_type = "INT"
    geom_op_61.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_59.outputs["Dual Mesh"], geom_op_61.inputs["Geometry"])
    node_tree.links.new(field_60.outputs["Index"], geom_op_61.inputs["Value"])
    field_62 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_62.location = (14700, 0)
    field_62.label = 'edge_vertices'
    field_63 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_63.location = (15000, 0)
    field_63.label = 'edge_vertices'
    math_64 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_64.location = (15300, 0)
    math_64.label = 'vec_add'
    math_64.operation = "ADD"
    node_tree.links.new(field_62.outputs["Position 1"], math_64.inputs["Vector"])
    node_tree.links.new(field_63.outputs["Position 2"], math_64.inputs["Vector_001"])
    val_65 = node_tree.nodes.new("ShaderNodeValue")
    val_65.location = (15300, 280)
    val_65.label = 'half'
    val_65.outputs[0].default_value = 0.5
    math_66 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_66.location = (15600, 0)
    math_66.label = 'vec_scale'
    math_66.operation = "SCALE"
    node_tree.links.new(math_64.outputs["Vector"], math_66.inputs["Vector"])
    node_tree.links.new(val_65.outputs["Value"], math_66.inputs["Scale"])
    vec_67 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_67.location = (15600, 280)
    vec_67.label = 'plane_mask'
    vec_67.vector = [1.0, 1.0, 0.0]
    math_68 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_68.location = (15900, 0)
    math_68.label = 'vec_multiply'
    math_68.operation = "MULTIPLY"
    node_tree.links.new(math_66.outputs["Vector"], math_68.inputs["Vector"])
    node_tree.links.new(vec_67.outputs["Vector"], math_68.inputs["Vector_001"])
    vec_69 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_69.location = (15900, 280)
    vec_69.label = 'plane_primary'
    vec_69.vector = [1.0, 0.0, 0.0]
    val_70 = node_tree.nodes.new("ShaderNodeValue")
    val_70.location = (15900, 560)
    val_70.label = 'pi'
    val_70.outputs[0].default_value = 3.141592653589793
    field_71 = node_tree.nodes.new("GeometryNodeInputMeshEdgeAngle")
    field_71.location = (16200, 0)
    field_71.label = 'edge_angle'
    math_72 = node_tree.nodes.new("ShaderNodeMath")
    math_72.location = (16500, 0)
    math_72.label = 'subtract'
    math_72.operation = "SUBTRACT"
    node_tree.links.new(val_70.outputs["Value"], math_72.inputs["Value"])
    node_tree.links.new(field_71.outputs["Unsigned Angle"], math_72.inputs["Value_001"])
    val_73 = node_tree.nodes.new("ShaderNodeValue")
    val_73.location = (16500, 280)
    val_73.label = 'half_angle_scale'
    val_73.outputs[0].default_value = 0.5
    math_74 = node_tree.nodes.new("ShaderNodeMath")
    math_74.location = (16800, 0)
    math_74.label = 'multiply'
    math_74.operation = "MULTIPLY"
    node_tree.links.new(math_72.outputs["Value"], math_74.inputs["Value"])
    node_tree.links.new(val_73.outputs["Value"], math_74.inputs["Value_001"])
    math_75 = node_tree.nodes.new("ShaderNodeMath")
    math_75.location = (17100, 0)
    math_75.label = 'cos'
    math_75.operation = "COSINE"
    node_tree.links.new(math_74.outputs["Value"], math_75.inputs["Value"])
    math_76 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_76.location = (17400, 0)
    math_76.label = 'vec_scale'
    math_76.operation = "SCALE"
    node_tree.links.new(vec_69.outputs["Vector"], math_76.inputs["Vector"])
    node_tree.links.new(math_75.outputs["Value"], math_76.inputs["Scale"])
    vec_77 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_77.location = (17400, 280)
    vec_77.label = 'plane_secondary'
    vec_77.vector = [0.0, 1.0, 0.0]
    val_78 = node_tree.nodes.new("ShaderNodeValue")
    val_78.location = (17400, 560)
    val_78.label = 'pi'
    val_78.outputs[0].default_value = 3.141592653589793
    field_79 = node_tree.nodes.new("GeometryNodeInputMeshEdgeAngle")
    field_79.location = (17700, 0)
    field_79.label = 'edge_angle'
    math_80 = node_tree.nodes.new("ShaderNodeMath")
    math_80.location = (18000, 0)
    math_80.label = 'subtract'
    math_80.operation = "SUBTRACT"
    node_tree.links.new(val_78.outputs["Value"], math_80.inputs["Value"])
    node_tree.links.new(field_79.outputs["Unsigned Angle"], math_80.inputs["Value_001"])
    val_81 = node_tree.nodes.new("ShaderNodeValue")
    val_81.location = (18000, 280)
    val_81.label = 'half_angle_scale'
    val_81.outputs[0].default_value = 0.5
    math_82 = node_tree.nodes.new("ShaderNodeMath")
    math_82.location = (18300, 0)
    math_82.label = 'multiply'
    math_82.operation = "MULTIPLY"
    node_tree.links.new(math_80.outputs["Value"], math_82.inputs["Value"])
    node_tree.links.new(val_81.outputs["Value"], math_82.inputs["Value_001"])
    math_83 = node_tree.nodes.new("ShaderNodeMath")
    math_83.location = (18600, 0)
    math_83.label = 'sin'
    math_83.operation = "SINE"
    node_tree.links.new(math_82.outputs["Value"], math_83.inputs["Value"])
    math_84 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_84.location = (18900, 0)
    math_84.label = 'vec_scale'
    math_84.operation = "SCALE"
    node_tree.links.new(vec_77.outputs["Vector"], math_84.inputs["Vector"])
    node_tree.links.new(math_83.outputs["Value"], math_84.inputs["Scale"])
    math_85 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_85.location = (19200, 0)
    math_85.label = 'vec_add'
    math_85.operation = "ADD"
    node_tree.links.new(math_76.outputs["Vector"], math_85.inputs["Vector"])
    node_tree.links.new(math_84.outputs["Vector"], math_85.inputs["Vector_001"])
    val_86 = node_tree.nodes.new("ShaderNodeValue")
    val_86.location = (19200, 280)
    val_86.label = 'arm_length'
    val_86.outputs[0].default_value = 0.3
    math_87 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_87.location = (19500, 0)
    math_87.label = 'vec_scale'
    math_87.operation = "SCALE"
    node_tree.links.new(math_85.outputs["Vector"], math_87.inputs["Vector"])
    node_tree.links.new(val_86.outputs["Value"], math_87.inputs["Scale"])
    math_88 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_88.location = (19800, 0)
    math_88.label = 'vec_add'
    math_88.operation = "ADD"
    node_tree.links.new(math_68.outputs["Vector"], math_88.inputs["Vector"])
    node_tree.links.new(math_87.outputs["Vector"], math_88.inputs["Vector_001"])
    geom_op_89 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_89.location = (20100, 0)
    geom_op_89.label = 'flat_edge_connectors_pt_0'
    geom_op_89.mode = "EDGES"
    node_tree.links.new(geom_op_61.outputs["Geometry"], geom_op_89.inputs["Mesh"])
    node_tree.links.new(math_88.outputs["Vector"], geom_op_89.inputs["Position"])
    val_90 = node_tree.nodes.new("ShaderNodeValue")
    val_90.location = (20100, 280)
    val_90.label = 'flat_edge_connectors_order_0'
    val_90.outputs[0].default_value = 0.0
    geom_op_91 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_91.location = (20400, 0)
    geom_op_91.label = 'flat_edge_connectors_store_order_0'
    geom_op_91.domain = "POINT"
    geom_op_91.data_type = "FLOAT"
    geom_op_91.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_89.outputs["Points"], geom_op_91.inputs["Geometry"])
    node_tree.links.new(val_90.outputs["Value"], geom_op_91.inputs["Value"])
    val_93 = node_tree.nodes.new("ShaderNodeValue")
    val_93.location = (20700, 280)
    val_93.label = 'dodeca_seed radius'
    val_93.outputs[0].default_value = 2.0
    prim_92 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_92.location = (20700, 0)
    prim_92.label = 'dodeca_seed'
    node_tree.links.new(val_93.outputs["Value"], prim_92.inputs["Radius"])
    prim_92.inputs["Subdivisions"].default_value = 1
    geom_op_94 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_94.location = (21000, 0)
    geom_op_94.label = 'dodeca_seed dual'
    geom_op_94.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_92.outputs["Mesh"], geom_op_94.inputs["Mesh"])
    field_95 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_95.location = (21300, 0)
    field_95.label = 'index'
    geom_op_96 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_96.location = (21600, 0)
    geom_op_96.label = 'flat_edge_connectors_edge_id'
    geom_op_96.domain = "EDGE"
    geom_op_96.data_type = "INT"
    geom_op_96.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_94.outputs["Dual Mesh"], geom_op_96.inputs["Geometry"])
    node_tree.links.new(field_95.outputs["Index"], geom_op_96.inputs["Value"])
    field_97 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_97.location = (21900, 0)
    field_97.label = 'edge_vertices'
    field_98 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_98.location = (22200, 0)
    field_98.label = 'edge_vertices'
    math_99 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_99.location = (22500, 0)
    math_99.label = 'vec_add'
    math_99.operation = "ADD"
    node_tree.links.new(field_97.outputs["Position 1"], math_99.inputs["Vector"])
    node_tree.links.new(field_98.outputs["Position 2"], math_99.inputs["Vector_001"])
    val_100 = node_tree.nodes.new("ShaderNodeValue")
    val_100.location = (22500, 280)
    val_100.label = 'half'
    val_100.outputs[0].default_value = 0.5
    math_101 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_101.location = (22800, 0)
    math_101.label = 'vec_scale'
    math_101.operation = "SCALE"
    node_tree.links.new(math_99.outputs["Vector"], math_101.inputs["Vector"])
    node_tree.links.new(val_100.outputs["Value"], math_101.inputs["Scale"])
    vec_102 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_102.location = (22800, 280)
    vec_102.label = 'plane_mask'
    vec_102.vector = [1.0, 1.0, 0.0]
    math_103 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_103.location = (23100, 0)
    math_103.label = 'vec_multiply'
    math_103.operation = "MULTIPLY"
    node_tree.links.new(math_101.outputs["Vector"], math_103.inputs["Vector"])
    node_tree.links.new(vec_102.outputs["Vector"], math_103.inputs["Vector_001"])
    geom_op_104 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_104.location = (23400, 0)
    geom_op_104.label = 'flat_edge_connectors_pt_1'
    geom_op_104.mode = "EDGES"
    node_tree.links.new(geom_op_96.outputs["Geometry"], geom_op_104.inputs["Mesh"])
    node_tree.links.new(math_103.outputs["Vector"], geom_op_104.inputs["Position"])
    val_105 = node_tree.nodes.new("ShaderNodeValue")
    val_105.location = (23400, 280)
    val_105.label = 'flat_edge_connectors_order_1'
    val_105.outputs[0].default_value = 1.0
    geom_op_106 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_106.location = (23700, 0)
    geom_op_106.label = 'flat_edge_connectors_store_order_1'
    geom_op_106.domain = "POINT"
    geom_op_106.data_type = "FLOAT"
    geom_op_106.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_104.outputs["Points"], geom_op_106.inputs["Geometry"])
    node_tree.links.new(val_105.outputs["Value"], geom_op_106.inputs["Value"])
    val_108 = node_tree.nodes.new("ShaderNodeValue")
    val_108.location = (24000, 280)
    val_108.label = 'dodeca_seed radius'
    val_108.outputs[0].default_value = 2.0
    prim_107 = node_tree.nodes.new("GeometryNodeMeshIcoSphere")
    prim_107.location = (24000, 0)
    prim_107.label = 'dodeca_seed'
    node_tree.links.new(val_108.outputs["Value"], prim_107.inputs["Radius"])
    prim_107.inputs["Subdivisions"].default_value = 1
    geom_op_109 = node_tree.nodes.new("GeometryNodeDualMesh")
    geom_op_109.location = (24300, 0)
    geom_op_109.label = 'dodeca_seed dual'
    geom_op_109.inputs["Keep Boundaries"].default_value = False
    node_tree.links.new(prim_107.outputs["Mesh"], geom_op_109.inputs["Mesh"])
    field_110 = node_tree.nodes.new("GeometryNodeInputIndex")
    field_110.location = (24600, 0)
    field_110.label = 'index'
    geom_op_111 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_111.location = (24900, 0)
    geom_op_111.label = 'flat_edge_connectors_edge_id'
    geom_op_111.domain = "EDGE"
    geom_op_111.data_type = "INT"
    geom_op_111.inputs["Name"].default_value = '_edge_id'
    node_tree.links.new(geom_op_109.outputs["Dual Mesh"], geom_op_111.inputs["Geometry"])
    node_tree.links.new(field_110.outputs["Index"], geom_op_111.inputs["Value"])
    field_112 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_112.location = (25200, 0)
    field_112.label = 'edge_vertices'
    field_113 = node_tree.nodes.new("GeometryNodeInputMeshEdgeVertices")
    field_113.location = (25500, 0)
    field_113.label = 'edge_vertices'
    math_114 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_114.location = (25800, 0)
    math_114.label = 'vec_add'
    math_114.operation = "ADD"
    node_tree.links.new(field_112.outputs["Position 1"], math_114.inputs["Vector"])
    node_tree.links.new(field_113.outputs["Position 2"], math_114.inputs["Vector_001"])
    val_115 = node_tree.nodes.new("ShaderNodeValue")
    val_115.location = (25800, 280)
    val_115.label = 'half'
    val_115.outputs[0].default_value = 0.5
    math_116 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_116.location = (26100, 0)
    math_116.label = 'vec_scale'
    math_116.operation = "SCALE"
    node_tree.links.new(math_114.outputs["Vector"], math_116.inputs["Vector"])
    node_tree.links.new(val_115.outputs["Value"], math_116.inputs["Scale"])
    vec_117 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_117.location = (26100, 280)
    vec_117.label = 'plane_mask'
    vec_117.vector = [1.0, 1.0, 0.0]
    math_118 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_118.location = (26400, 0)
    math_118.label = 'vec_multiply'
    math_118.operation = "MULTIPLY"
    node_tree.links.new(math_116.outputs["Vector"], math_118.inputs["Vector"])
    node_tree.links.new(vec_117.outputs["Vector"], math_118.inputs["Vector_001"])
    vec_119 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_119.location = (26400, 280)
    vec_119.label = 'plane_primary'
    vec_119.vector = [1.0, 0.0, 0.0]
    val_120 = node_tree.nodes.new("ShaderNodeValue")
    val_120.location = (26400, 560)
    val_120.label = 'pi'
    val_120.outputs[0].default_value = 3.141592653589793
    field_121 = node_tree.nodes.new("GeometryNodeInputMeshEdgeAngle")
    field_121.location = (26700, 0)
    field_121.label = 'edge_angle'
    math_122 = node_tree.nodes.new("ShaderNodeMath")
    math_122.location = (27000, 0)
    math_122.label = 'subtract'
    math_122.operation = "SUBTRACT"
    node_tree.links.new(val_120.outputs["Value"], math_122.inputs["Value"])
    node_tree.links.new(field_121.outputs["Unsigned Angle"], math_122.inputs["Value_001"])
    val_123 = node_tree.nodes.new("ShaderNodeValue")
    val_123.location = (27000, 280)
    val_123.label = 'half_angle_scale'
    val_123.outputs[0].default_value = 0.5
    math_124 = node_tree.nodes.new("ShaderNodeMath")
    math_124.location = (27300, 0)
    math_124.label = 'multiply'
    math_124.operation = "MULTIPLY"
    node_tree.links.new(math_122.outputs["Value"], math_124.inputs["Value"])
    node_tree.links.new(val_123.outputs["Value"], math_124.inputs["Value_001"])
    math_125 = node_tree.nodes.new("ShaderNodeMath")
    math_125.location = (27600, 0)
    math_125.label = 'cos'
    math_125.operation = "COSINE"
    node_tree.links.new(math_124.outputs["Value"], math_125.inputs["Value"])
    math_126 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_126.location = (27900, 0)
    math_126.label = 'vec_scale'
    math_126.operation = "SCALE"
    node_tree.links.new(vec_119.outputs["Vector"], math_126.inputs["Vector"])
    node_tree.links.new(math_125.outputs["Value"], math_126.inputs["Scale"])
    vec_127 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_127.location = (27900, 280)
    vec_127.label = 'plane_secondary'
    vec_127.vector = [0.0, 1.0, 0.0]
    val_128 = node_tree.nodes.new("ShaderNodeValue")
    val_128.location = (27900, 560)
    val_128.label = 'pi'
    val_128.outputs[0].default_value = 3.141592653589793
    field_129 = node_tree.nodes.new("GeometryNodeInputMeshEdgeAngle")
    field_129.location = (28200, 0)
    field_129.label = 'edge_angle'
    math_130 = node_tree.nodes.new("ShaderNodeMath")
    math_130.location = (28500, 0)
    math_130.label = 'subtract'
    math_130.operation = "SUBTRACT"
    node_tree.links.new(val_128.outputs["Value"], math_130.inputs["Value"])
    node_tree.links.new(field_129.outputs["Unsigned Angle"], math_130.inputs["Value_001"])
    val_131 = node_tree.nodes.new("ShaderNodeValue")
    val_131.location = (28500, 280)
    val_131.label = 'half_angle_scale'
    val_131.outputs[0].default_value = 0.5
    math_132 = node_tree.nodes.new("ShaderNodeMath")
    math_132.location = (28800, 0)
    math_132.label = 'multiply'
    math_132.operation = "MULTIPLY"
    node_tree.links.new(math_130.outputs["Value"], math_132.inputs["Value"])
    node_tree.links.new(val_131.outputs["Value"], math_132.inputs["Value_001"])
    math_133 = node_tree.nodes.new("ShaderNodeMath")
    math_133.location = (29100, 0)
    math_133.label = 'sin'
    math_133.operation = "SINE"
    node_tree.links.new(math_132.outputs["Value"], math_133.inputs["Value"])
    val_134 = node_tree.nodes.new("ShaderNodeValue")
    val_134.location = (29100, 280)
    val_134.label = 'neg_one'
    val_134.outputs[0].default_value = -1.0
    math_135 = node_tree.nodes.new("ShaderNodeMath")
    math_135.location = (29400, 0)
    math_135.label = 'multiply'
    math_135.operation = "MULTIPLY"
    node_tree.links.new(math_133.outputs["Value"], math_135.inputs["Value"])
    node_tree.links.new(val_134.outputs["Value"], math_135.inputs["Value_001"])
    math_136 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_136.location = (29700, 0)
    math_136.label = 'vec_scale'
    math_136.operation = "SCALE"
    node_tree.links.new(vec_127.outputs["Vector"], math_136.inputs["Vector"])
    node_tree.links.new(math_135.outputs["Value"], math_136.inputs["Scale"])
    math_137 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_137.location = (30000, 0)
    math_137.label = 'vec_add'
    math_137.operation = "ADD"
    node_tree.links.new(math_126.outputs["Vector"], math_137.inputs["Vector"])
    node_tree.links.new(math_136.outputs["Vector"], math_137.inputs["Vector_001"])
    val_138 = node_tree.nodes.new("ShaderNodeValue")
    val_138.location = (30000, 280)
    val_138.label = 'arm_length'
    val_138.outputs[0].default_value = 0.3
    math_139 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_139.location = (30300, 0)
    math_139.label = 'vec_scale'
    math_139.operation = "SCALE"
    node_tree.links.new(math_137.outputs["Vector"], math_139.inputs["Vector"])
    node_tree.links.new(val_138.outputs["Value"], math_139.inputs["Scale"])
    math_140 = node_tree.nodes.new("ShaderNodeVectorMath")
    math_140.location = (30600, 0)
    math_140.label = 'vec_add'
    math_140.operation = "ADD"
    node_tree.links.new(math_118.outputs["Vector"], math_140.inputs["Vector"])
    node_tree.links.new(math_139.outputs["Vector"], math_140.inputs["Vector_001"])
    geom_op_141 = node_tree.nodes.new("GeometryNodeMeshToPoints")
    geom_op_141.location = (30900, 0)
    geom_op_141.label = 'flat_edge_connectors_pt_2'
    geom_op_141.mode = "EDGES"
    node_tree.links.new(geom_op_111.outputs["Geometry"], geom_op_141.inputs["Mesh"])
    node_tree.links.new(math_140.outputs["Vector"], geom_op_141.inputs["Position"])
    val_142 = node_tree.nodes.new("ShaderNodeValue")
    val_142.location = (30900, 280)
    val_142.label = 'flat_edge_connectors_order_2'
    val_142.outputs[0].default_value = 2.0
    geom_op_143 = node_tree.nodes.new("GeometryNodeStoreNamedAttribute")
    geom_op_143.location = (31200, 0)
    geom_op_143.label = 'flat_edge_connectors_store_order_2'
    geom_op_143.domain = "POINT"
    geom_op_143.data_type = "FLOAT"
    geom_op_143.inputs["Name"].default_value = '_point_order'
    node_tree.links.new(geom_op_141.outputs["Points"], geom_op_143.inputs["Geometry"])
    node_tree.links.new(val_142.outputs["Value"], geom_op_143.inputs["Value"])
    join_144 = node_tree.nodes.new("GeometryNodeJoinGeometry")
    join_144.location = (31500, 0)
    join_144.label = 'flat_edge_connectors_points'
    node_tree.links.new(geom_op_91.outputs["Geometry"], join_144.inputs["Geometry"])
    node_tree.links.new(geom_op_106.outputs["Geometry"], join_144.inputs["Geometry"])
    node_tree.links.new(geom_op_143.outputs["Geometry"], join_144.inputs["Geometry"])
    field_145 = node_tree.nodes.new("GeometryNodeInputNamedAttribute")
    field_145.location = (31800, 0)
    field_145.label = 'attr:_edge_id'
    field_145.data_type = "INT"
    field_145.inputs["Name"].default_value = "_edge_id"
    field_146 = node_tree.nodes.new("GeometryNodeInputNamedAttribute")
    field_146.location = (32100, 0)
    field_146.label = 'attr:_point_order'
    field_146.data_type = "FLOAT"
    field_146.inputs["Name"].default_value = "_point_order"
    geom_op_147 = node_tree.nodes.new("GeometryNodePointsToCurves")
    geom_op_147.location = (32400, 0)
    geom_op_147.label = 'flat_edge_connectors'
    node_tree.links.new(join_144.outputs["Geometry"], geom_op_147.inputs["Points"])
    node_tree.links.new(field_145.outputs["Attribute"], geom_op_147.inputs["Curve Group ID"])
    node_tree.links.new(field_146.outputs["Attribute"], geom_op_147.inputs["Weight"])
    join_148 = node_tree.nodes.new("GeometryNodeJoinGeometry")
    join_148.location = (32700, 0)
    join_148.label = 'mesh_analysis'
    node_tree.links.new(geom_op_4.outputs["Curve"], join_148.inputs["Geometry"])
    node_tree.links.new(geom_op_7.outputs["Dual Mesh"], join_148.inputs["Geometry"])
    node_tree.links.new(geom_op_56.outputs["Curves"], join_148.inputs["Geometry"])
    node_tree.links.new(geom_op_147.outputs["Curves"], join_148.inputs["Geometry"])
    out_149 = node_tree.nodes.new("NodeGroupOutput")
    out_149.location = (33000, 0)
    out_149.label = "output"
    node_tree.links.new(join_148.outputs[0], out_149.inputs[0])

    return node_tree





# Execute all parts
setup_dodecahedron_mesh_analysis()
