import bpy


def setup_lamp_joint_7(object_name='lamp_joint_7'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (0, 280)
    vec_2.label = "base size"
    vec_2.vector = [40, 160, 46]
    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 0)
    prim_1.label = 'base'
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    val_4 = node_tree.nodes.new("ShaderNodeValue")
    val_4.location = (300, 280)
    val_4.label = 'h_wood radius'
    val_4.outputs[0].default_value = 13.0
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (300, 560)
    val_5.label = 'h_wood depth'
    val_5.outputs[0].default_value = 60
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_3.location = (300, 0)
    prim_3.label = 'h_wood'
    node_tree.links.new(val_4.outputs["Value"], prim_3.inputs["Radius"])
    node_tree.links.new(val_5.outputs["Value"], prim_3.inputs["Depth"])
    prim_3.inputs["Vertices"].default_value = 128
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (600, 280)
    vec_7.label = 'h_wood rotate rotation'
    vec_7.vector = [1.5707963267948966, 0.0, 1.5707963267948966]
    xform_6 = node_tree.nodes.new("GeometryNodeTransform")
    xform_6.location = (600, 0)
    xform_6.label = 'h_wood rotate'
    node_tree.links.new(prim_3.outputs["Mesh"], xform_6.inputs["Geometry"])
    node_tree.links.new(vec_7.outputs["Vector"], xform_6.inputs["Rotation"])
    bool_8 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_8.location = (900, 0)
    bool_8.label = 'difference'
    bool_8.operation = "DIFFERENCE"
    bool_8.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_8.inputs[0])
    node_tree.links.new(xform_6.outputs["Geometry"], bool_8.inputs[1])
    out_9 = node_tree.nodes.new("NodeGroupOutput")
    out_9.location = (1200, 0)
    out_9.label = "output"
    node_tree.links.new(bool_8.outputs[0], out_9.inputs[0])

    return node_tree





# Execute all parts
setup_lamp_joint_7()
