import bpy


def setup(object_name='base_cam'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'base_cam'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "base_cam size"
    vec_2.vector = [50, 50, 10]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_3.location = (0, 400)
    prim_3.label = 'h_nonslip'
    val_4 = node_tree.nodes.new("ShaderNodeValue")
    val_4.location = (180, 400)
    val_4.label = 'h_nonslip radius'
    val_4.outputs[0].default_value = 4
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (360, 400)
    val_5.label = 'h_nonslip depth'
    val_5.outputs[0].default_value = 6
    node_tree.links.new(val_4.outputs["Value"], prim_3.inputs["Radius"])
    node_tree.links.new(val_5.outputs["Value"], prim_3.inputs["Depth"])
    prim_3.inputs["Vertices"].default_value = 32
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (0, 600)
    setpos_6.label = 'h_nonslip position'
    node_tree.links.new(prim_3.outputs["Mesh"], setpos_6.inputs["Geometry"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (180, 600)
    vec_7.label = 'h_nonslip position offset'
    vec_7.vector = [18, 18, -4]
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (0, 800)
    prim_8.label = 'h_nonslip'
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (180, 800)
    val_9.label = 'h_nonslip radius'
    val_9.outputs[0].default_value = 4
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (360, 800)
    val_10.label = 'h_nonslip depth'
    val_10.outputs[0].default_value = 6
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 32
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (0, 1000)
    setpos_11.label = 'h_nonslip position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_11.inputs["Geometry"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (180, 1000)
    vec_12.label = 'h_nonslip position offset'
    vec_12.vector = [-18, 18, -4]
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_13.location = (0, 1200)
    prim_13.label = 'h_nonslip'
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (180, 1200)
    val_14.label = 'h_nonslip radius'
    val_14.outputs[0].default_value = 4
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (360, 1200)
    val_15.label = 'h_nonslip depth'
    val_15.outputs[0].default_value = 6
    node_tree.links.new(val_14.outputs["Value"], prim_13.inputs["Radius"])
    node_tree.links.new(val_15.outputs["Value"], prim_13.inputs["Depth"])
    prim_13.inputs["Vertices"].default_value = 32
    setpos_16 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_16.location = (0, 1400)
    setpos_16.label = 'h_nonslip position'
    node_tree.links.new(prim_13.outputs["Mesh"], setpos_16.inputs["Geometry"])
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (180, 1400)
    vec_17.label = 'h_nonslip position offset'
    vec_17.vector = [18, -18, -4]
    node_tree.links.new(vec_17.outputs["Vector"], setpos_16.inputs["Offset"])
    prim_18 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_18.location = (0, 1600)
    prim_18.label = 'h_nonslip'
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (180, 1600)
    val_19.label = 'h_nonslip radius'
    val_19.outputs[0].default_value = 4
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (360, 1600)
    val_20.label = 'h_nonslip depth'
    val_20.outputs[0].default_value = 6
    node_tree.links.new(val_19.outputs["Value"], prim_18.inputs["Radius"])
    node_tree.links.new(val_20.outputs["Value"], prim_18.inputs["Depth"])
    prim_18.inputs["Vertices"].default_value = 32
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (0, 1800)
    setpos_21.label = 'h_nonslip position'
    node_tree.links.new(prim_18.outputs["Mesh"], setpos_21.inputs["Geometry"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (180, 1800)
    vec_22.label = 'h_nonslip position offset'
    vec_22.vector = [-18, -18, -4]
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (0, 2000)
    prim_23.label = 'h_screw'
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (180, 2000)
    val_24.label = 'h_screw radius'
    val_24.outputs[0].default_value = 4
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (360, 2000)
    val_25.label = 'h_screw depth'
    val_25.outputs[0].default_value = 30
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (0, 2200)
    prim_26.label = 'h_screw'
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (180, 2200)
    val_27.label = 'h_screw radius'
    val_27.outputs[0].default_value = 8
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (360, 2200)
    val_28.label = 'h_screw depth'
    val_28.outputs[0].default_value = 6
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (0, 2400)
    setpos_29.label = 'h_screw position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_29.inputs["Geometry"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2400)
    vec_30.label = 'h_screw position offset'
    vec_30.vector = [0, 0, -2]
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_31.location = (0, 2600)
    prim_31.label = 'h_light'
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (180, 2600)
    vec_32.label = "h_light size"
    vec_32.vector = [21, 50, 10]
    node_tree.links.new(vec_32.outputs["Vector"], prim_31.inputs["Size"])
    setpos_33 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_33.location = (0, 2800)
    setpos_33.label = 'h_light position'
    node_tree.links.new(prim_31.outputs["Mesh"], setpos_33.inputs["Geometry"])
    vec_34 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_34.location = (180, 2800)
    vec_34.label = 'h_light position offset'
    vec_34.vector = [0, 0, 8]
    node_tree.links.new(vec_34.outputs["Vector"], setpos_33.inputs["Offset"])
    bool_35 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_35.location = (0, 3000)
    bool_35.label = 'difference'
    bool_35.operation = "DIFFERENCE"
    bool_35.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_35.inputs[0])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_16.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(prim_23.outputs["Mesh"], bool_35.inputs[1])
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_33.outputs["Geometry"], bool_35.inputs[1])
    prim_36 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_36.location = (0, 3200)
    prim_36.label = 'base_columns'
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (180, 3200)
    vec_37.label = "base_columns size"
    vec_37.vector = [14, 14, 20]
    node_tree.links.new(vec_37.outputs["Vector"], prim_36.inputs["Size"])
    setpos_38 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_38.location = (0, 3400)
    setpos_38.label = 'base_columns position'
    node_tree.links.new(prim_36.outputs["Mesh"], setpos_38.inputs["Geometry"])
    vec_39 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_39.location = (180, 3400)
    vec_39.label = 'base_columns position offset'
    vec_39.vector = [18, 15, 12]
    node_tree.links.new(vec_39.outputs["Vector"], setpos_38.inputs["Offset"])
    prim_40 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_40.location = (0, 3600)
    prim_40.label = 'column3'
    val_41 = node_tree.nodes.new("ShaderNodeValue")
    val_41.location = (180, 3600)
    val_41.label = 'column3 radius'
    val_41.outputs[0].default_value = 4.925
    val_42 = node_tree.nodes.new("ShaderNodeValue")
    val_42.location = (360, 3600)
    val_42.label = 'column3 depth'
    val_42.outputs[0].default_value = 13
    node_tree.links.new(val_41.outputs["Value"], prim_40.inputs["Radius"])
    node_tree.links.new(val_42.outputs["Value"], prim_40.inputs["Depth"])
    prim_40.inputs["Vertices"].default_value = 32
    xform_43 = node_tree.nodes.new("GeometryNodeTransform")
    xform_43.location = (0, 3800)
    xform_43.label = 'column3 rotate'
    node_tree.links.new(prim_40.outputs["Mesh"], xform_43.inputs["Geometry"])
    vec_44 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_44.location = (180, 3800)
    vec_44.label = 'column3 rotate rotation'
    vec_44.vector = [1.5707963267948966, 0.0, 1.5707963267948966]
    node_tree.links.new(vec_44.outputs["Vector"], xform_43.inputs["Rotation"])
    setpos_45 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_45.location = (0, 4000)
    setpos_45.label = 'column3 rotate position'
    node_tree.links.new(xform_43.outputs["Geometry"], setpos_45.inputs["Geometry"])
    vec_46 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_46.location = (180, 4000)
    vec_46.label = 'column3 rotate position offset'
    vec_46.vector = [19, 15, 16]
    node_tree.links.new(vec_46.outputs["Vector"], setpos_45.inputs["Offset"])
    bool_47 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_47.location = (0, 4200)
    bool_47.label = 'difference'
    bool_47.operation = "DIFFERENCE"
    bool_47.solver = "EXACT"
    node_tree.links.new(setpos_38.outputs["Geometry"], bool_47.inputs[0])
    node_tree.links.new(setpos_45.outputs["Geometry"], bool_47.inputs[1])
    prim_48 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_48.location = (0, 4400)
    prim_48.label = 'base_columns'
    vec_49 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_49.location = (180, 4400)
    vec_49.label = "base_columns size"
    vec_49.vector = [14, 14, 20]
    node_tree.links.new(vec_49.outputs["Vector"], prim_48.inputs["Size"])
    setpos_50 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_50.location = (0, 4600)
    setpos_50.label = 'base_columns position'
    node_tree.links.new(prim_48.outputs["Mesh"], setpos_50.inputs["Geometry"])
    vec_51 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_51.location = (180, 4600)
    vec_51.label = 'base_columns position offset'
    vec_51.vector = [18, 15, 12]
    node_tree.links.new(vec_51.outputs["Vector"], setpos_50.inputs["Offset"])
    prim_52 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_52.location = (0, 4800)
    prim_52.label = 'column3'
    val_53 = node_tree.nodes.new("ShaderNodeValue")
    val_53.location = (180, 4800)
    val_53.label = 'column3 radius'
    val_53.outputs[0].default_value = 4.925
    val_54 = node_tree.nodes.new("ShaderNodeValue")
    val_54.location = (360, 4800)
    val_54.label = 'column3 depth'
    val_54.outputs[0].default_value = 13
    node_tree.links.new(val_53.outputs["Value"], prim_52.inputs["Radius"])
    node_tree.links.new(val_54.outputs["Value"], prim_52.inputs["Depth"])
    prim_52.inputs["Vertices"].default_value = 32
    xform_55 = node_tree.nodes.new("GeometryNodeTransform")
    xform_55.location = (0, 5000)
    xform_55.label = 'column3 rotate'
    node_tree.links.new(prim_52.outputs["Mesh"], xform_55.inputs["Geometry"])
    vec_56 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_56.location = (180, 5000)
    vec_56.label = 'column3 rotate rotation'
    vec_56.vector = [1.5707963267948966, 0.0, 1.5707963267948966]
    node_tree.links.new(vec_56.outputs["Vector"], xform_55.inputs["Rotation"])
    setpos_57 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_57.location = (0, 5200)
    setpos_57.label = 'column3 rotate position'
    node_tree.links.new(xform_55.outputs["Geometry"], setpos_57.inputs["Geometry"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (180, 5200)
    vec_58.label = 'column3 rotate position offset'
    vec_58.vector = [19, 15, 16]
    node_tree.links.new(vec_58.outputs["Vector"], setpos_57.inputs["Offset"])
    bool_59 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_59.location = (0, 5400)
    bool_59.label = 'difference'
    bool_59.operation = "DIFFERENCE"
    bool_59.solver = "EXACT"
    node_tree.links.new(setpos_50.outputs["Geometry"], bool_59.inputs[0])
    node_tree.links.new(setpos_57.outputs["Geometry"], bool_59.inputs[1])
    xform_60 = node_tree.nodes.new("GeometryNodeTransform")
    xform_60.location = (0, 5600)
    xform_60.label = 'difference translate'
    node_tree.links.new(bool_59.outputs["Mesh"], xform_60.inputs["Geometry"])
    vec_61 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_61.location = (180, 5600)
    vec_61.label = 'difference translate translation'
    vec_61.vector = [0, -30, 0]
    node_tree.links.new(vec_61.outputs["Vector"], xform_60.inputs["Translation"])
    bool_62 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_62.location = (0, 5800)
    bool_62.label = 'union'
    bool_62.operation = "UNION"
    bool_62.solver = "EXACT"
    node_tree.links.new(bool_35.outputs["Mesh"], bool_62.inputs[1])
    node_tree.links.new(bool_47.outputs["Mesh"], bool_62.inputs[1])
    node_tree.links.new(xform_60.outputs["Geometry"], bool_62.inputs[1])
    out_63 = node_tree.nodes.new("NodeGroupOutput")
    out_63.location = (0, 6000)
    out_63.label = "output"
    node_tree.links.new(bool_62.outputs[0], out_63.inputs[0])

    return node_tree


# Execute
setup()

