import bpy


def setup(object_name='columns'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'column1'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'column1 radius'
    val_2.outputs[0].default_value = 4.925
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'column1 depth'
    val_3.outputs[0].default_value = 200
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    setpos_4 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_4.location = (0, 400)
    setpos_4.label = 'column1 position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_4.inputs["Geometry"])
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = 'column1 position offset'
    vec_5.vector = [30, 30, 0]
    node_tree.links.new(vec_5.outputs["Vector"], setpos_4.inputs["Offset"])
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (0, 600)
    prim_6.label = 'column2'
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (180, 600)
    val_7.label = 'column2 radius'
    val_7.outputs[0].default_value = 4.925
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (360, 600)
    val_8.label = 'column2 depth'
    val_8.outputs[0].default_value = 200
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 32
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 800)
    setpos_9.label = 'column2 position'
    node_tree.links.new(prim_6.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 800)
    vec_10.label = 'column2 position offset'
    vec_10.vector = [-30, 30, 0]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_11.location = (0, 1000)
    prim_11.label = 'column3'
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (180, 1000)
    val_12.label = 'column3 radius'
    val_12.outputs[0].default_value = 4.925
    val_13 = node_tree.nodes.new("ShaderNodeValue")
    val_13.location = (360, 1000)
    val_13.label = 'column3 depth'
    val_13.outputs[0].default_value = 200
    node_tree.links.new(val_12.outputs["Value"], prim_11.inputs["Radius"])
    node_tree.links.new(val_13.outputs["Value"], prim_11.inputs["Depth"])
    prim_11.inputs["Vertices"].default_value = 32
    setpos_14 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_14.location = (0, 1200)
    setpos_14.label = 'column3 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_14.inputs["Geometry"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (180, 1200)
    vec_15.label = 'column3 position offset'
    vec_15.vector = [30, -30, 0]
    node_tree.links.new(vec_15.outputs["Vector"], setpos_14.inputs["Offset"])
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (0, 1400)
    prim_16.label = 'column4'
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (180, 1400)
    val_17.label = 'column4 radius'
    val_17.outputs[0].default_value = 4.925
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (360, 1400)
    val_18.label = 'column4 depth'
    val_18.outputs[0].default_value = 200
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    setpos_19 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_19.location = (0, 1600)
    setpos_19.label = 'column4 position'
    node_tree.links.new(prim_16.outputs["Mesh"], setpos_19.inputs["Geometry"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (180, 1600)
    vec_20.label = 'column4 position offset'
    vec_20.vector = [-30, -30, 0]
    node_tree.links.new(vec_20.outputs["Vector"], setpos_19.inputs["Offset"])
    bool_21 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_21.location = (0, 1800)
    bool_21.label = 'union'
    bool_21.operation = "UNION"
    bool_21.solver = "EXACT"
    node_tree.links.new(setpos_4.outputs["Geometry"], bool_21.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_21.inputs[1])
    node_tree.links.new(setpos_14.outputs["Geometry"], bool_21.inputs[1])
    node_tree.links.new(setpos_19.outputs["Geometry"], bool_21.inputs[1])
    xform_22 = node_tree.nodes.new("GeometryNodeTransform")
    xform_22.location = (0, 2000)
    xform_22.label = 'union translate'
    node_tree.links.new(bool_21.outputs["Mesh"], xform_22.inputs["Geometry"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (180, 2000)
    vec_23.label = 'union translate translation'
    vec_23.vector = [0, 0, 70]
    node_tree.links.new(vec_23.outputs["Vector"], xform_22.inputs["Translation"])
    out_24 = node_tree.nodes.new("NodeGroupOutput")
    out_24.location = (0, 2200)
    out_24.label = "output"
    node_tree.links.new(xform_22.outputs[0], out_24.inputs[0])

    return node_tree


# Execute
setup()

