import bpy


def setup(object_name='cover'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'base'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "base size"
    vec_2.vector = [60, 5, 10]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'base position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'base position offset'
    vec_4.vector = [0, 30, 0]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (0, 600)
    prim_5.label = 'base'
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (180, 600)
    vec_6.label = "base size"
    vec_6.vector = [60, 5, 10]
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    setpos_7 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_7.location = (0, 800)
    setpos_7.label = 'base position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_7.inputs["Geometry"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (180, 800)
    vec_8.label = 'base position offset'
    vec_8.vector = [0, -30, 0]
    node_tree.links.new(vec_8.outputs["Vector"], setpos_7.inputs["Offset"])
    prim_9 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_9.location = (0, 1000)
    prim_9.label = 'base'
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 1000)
    vec_10.label = "base size"
    vec_10.vector = [5, 60, 10]
    node_tree.links.new(vec_10.outputs["Vector"], prim_9.inputs["Size"])
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (0, 1200)
    setpos_11.label = 'base position'
    node_tree.links.new(prim_9.outputs["Mesh"], setpos_11.inputs["Geometry"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (180, 1200)
    vec_12.label = 'base position offset'
    vec_12.vector = [30, 0, 0]
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_13.location = (0, 1400)
    prim_13.label = 'base'
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1400)
    vec_14.label = "base size"
    vec_14.vector = [5, 60, 10]
    node_tree.links.new(vec_14.outputs["Vector"], prim_13.inputs["Size"])
    setpos_15 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_15.location = (0, 1600)
    setpos_15.label = 'base position'
    node_tree.links.new(prim_13.outputs["Mesh"], setpos_15.inputs["Geometry"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (180, 1600)
    vec_16.label = 'base position offset'
    vec_16.vector = [-30, 0, 0]
    node_tree.links.new(vec_16.outputs["Vector"], setpos_15.inputs["Offset"])
    prim_17 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_17.location = (0, 1800)
    prim_17.label = 'column1'
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (180, 1800)
    val_18.label = 'column1 radius'
    val_18.outputs[0].default_value = 6.925
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (360, 1800)
    val_19.label = 'column1 depth'
    val_19.outputs[0].default_value = 10
    node_tree.links.new(val_18.outputs["Value"], prim_17.inputs["Radius"])
    node_tree.links.new(val_19.outputs["Value"], prim_17.inputs["Depth"])
    prim_17.inputs["Vertices"].default_value = 32
    setpos_20 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_20.location = (0, 2000)
    setpos_20.label = 'column1 position'
    node_tree.links.new(prim_17.outputs["Mesh"], setpos_20.inputs["Geometry"])
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (180, 2000)
    vec_21.label = 'column1 position offset'
    vec_21.vector = [30, 30, 0]
    node_tree.links.new(vec_21.outputs["Vector"], setpos_20.inputs["Offset"])
    prim_22 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_22.location = (0, 2200)
    prim_22.label = 'column2'
    val_23 = node_tree.nodes.new("ShaderNodeValue")
    val_23.location = (180, 2200)
    val_23.label = 'column2 radius'
    val_23.outputs[0].default_value = 6.925
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (360, 2200)
    val_24.label = 'column2 depth'
    val_24.outputs[0].default_value = 10
    node_tree.links.new(val_23.outputs["Value"], prim_22.inputs["Radius"])
    node_tree.links.new(val_24.outputs["Value"], prim_22.inputs["Depth"])
    prim_22.inputs["Vertices"].default_value = 32
    setpos_25 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_25.location = (0, 2400)
    setpos_25.label = 'column2 position'
    node_tree.links.new(prim_22.outputs["Mesh"], setpos_25.inputs["Geometry"])
    vec_26 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_26.location = (180, 2400)
    vec_26.label = 'column2 position offset'
    vec_26.vector = [-30, 30, 0]
    node_tree.links.new(vec_26.outputs["Vector"], setpos_25.inputs["Offset"])
    prim_27 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_27.location = (0, 2600)
    prim_27.label = 'column3'
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (180, 2600)
    val_28.label = 'column3 radius'
    val_28.outputs[0].default_value = 6.925
    val_29 = node_tree.nodes.new("ShaderNodeValue")
    val_29.location = (360, 2600)
    val_29.label = 'column3 depth'
    val_29.outputs[0].default_value = 10
    node_tree.links.new(val_28.outputs["Value"], prim_27.inputs["Radius"])
    node_tree.links.new(val_29.outputs["Value"], prim_27.inputs["Depth"])
    prim_27.inputs["Vertices"].default_value = 32
    setpos_30 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_30.location = (0, 2800)
    setpos_30.label = 'column3 position'
    node_tree.links.new(prim_27.outputs["Mesh"], setpos_30.inputs["Geometry"])
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (180, 2800)
    vec_31.label = 'column3 position offset'
    vec_31.vector = [30, -30, 0]
    node_tree.links.new(vec_31.outputs["Vector"], setpos_30.inputs["Offset"])
    prim_32 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_32.location = (0, 3000)
    prim_32.label = 'column4'
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (180, 3000)
    val_33.label = 'column4 radius'
    val_33.outputs[0].default_value = 6.925
    val_34 = node_tree.nodes.new("ShaderNodeValue")
    val_34.location = (360, 3000)
    val_34.label = 'column4 depth'
    val_34.outputs[0].default_value = 10
    node_tree.links.new(val_33.outputs["Value"], prim_32.inputs["Radius"])
    node_tree.links.new(val_34.outputs["Value"], prim_32.inputs["Depth"])
    prim_32.inputs["Vertices"].default_value = 32
    setpos_35 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_35.location = (0, 3200)
    setpos_35.label = 'column4 position'
    node_tree.links.new(prim_32.outputs["Mesh"], setpos_35.inputs["Geometry"])
    vec_36 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_36.location = (180, 3200)
    vec_36.label = 'column4 position offset'
    vec_36.vector = [-30, -30, 0]
    node_tree.links.new(vec_36.outputs["Vector"], setpos_35.inputs["Offset"])
    bool_37 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_37.location = (0, 3400)
    bool_37.label = 'union'
    bool_37.operation = "UNION"
    bool_37.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_7.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_15.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_20.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_25.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_30.outputs["Geometry"], bool_37.inputs[1])
    node_tree.links.new(setpos_35.outputs["Geometry"], bool_37.inputs[1])
    prim_38 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_38.location = (0, 3600)
    prim_38.label = 'column1'
    val_39 = node_tree.nodes.new("ShaderNodeValue")
    val_39.location = (180, 3600)
    val_39.label = 'column1 radius'
    val_39.outputs[0].default_value = 4.925
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (360, 3600)
    val_40.label = 'column1 depth'
    val_40.outputs[0].default_value = 10
    node_tree.links.new(val_39.outputs["Value"], prim_38.inputs["Radius"])
    node_tree.links.new(val_40.outputs["Value"], prim_38.inputs["Depth"])
    prim_38.inputs["Vertices"].default_value = 32
    setpos_41 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_41.location = (0, 3800)
    setpos_41.label = 'column1 position'
    node_tree.links.new(prim_38.outputs["Mesh"], setpos_41.inputs["Geometry"])
    vec_42 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_42.location = (180, 3800)
    vec_42.label = 'column1 position offset'
    vec_42.vector = [30, 30, 2]
    node_tree.links.new(vec_42.outputs["Vector"], setpos_41.inputs["Offset"])
    prim_43 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_43.location = (0, 4000)
    prim_43.label = 'column2'
    val_44 = node_tree.nodes.new("ShaderNodeValue")
    val_44.location = (180, 4000)
    val_44.label = 'column2 radius'
    val_44.outputs[0].default_value = 4.925
    val_45 = node_tree.nodes.new("ShaderNodeValue")
    val_45.location = (360, 4000)
    val_45.label = 'column2 depth'
    val_45.outputs[0].default_value = 10
    node_tree.links.new(val_44.outputs["Value"], prim_43.inputs["Radius"])
    node_tree.links.new(val_45.outputs["Value"], prim_43.inputs["Depth"])
    prim_43.inputs["Vertices"].default_value = 32
    setpos_46 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_46.location = (0, 4200)
    setpos_46.label = 'column2 position'
    node_tree.links.new(prim_43.outputs["Mesh"], setpos_46.inputs["Geometry"])
    vec_47 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_47.location = (180, 4200)
    vec_47.label = 'column2 position offset'
    vec_47.vector = [-30, 30, 2]
    node_tree.links.new(vec_47.outputs["Vector"], setpos_46.inputs["Offset"])
    prim_48 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_48.location = (0, 4400)
    prim_48.label = 'column3'
    val_49 = node_tree.nodes.new("ShaderNodeValue")
    val_49.location = (180, 4400)
    val_49.label = 'column3 radius'
    val_49.outputs[0].default_value = 4.925
    val_50 = node_tree.nodes.new("ShaderNodeValue")
    val_50.location = (360, 4400)
    val_50.label = 'column3 depth'
    val_50.outputs[0].default_value = 10
    node_tree.links.new(val_49.outputs["Value"], prim_48.inputs["Radius"])
    node_tree.links.new(val_50.outputs["Value"], prim_48.inputs["Depth"])
    prim_48.inputs["Vertices"].default_value = 32
    setpos_51 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_51.location = (0, 4600)
    setpos_51.label = 'column3 position'
    node_tree.links.new(prim_48.outputs["Mesh"], setpos_51.inputs["Geometry"])
    vec_52 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_52.location = (180, 4600)
    vec_52.label = 'column3 position offset'
    vec_52.vector = [30, -30, 2]
    node_tree.links.new(vec_52.outputs["Vector"], setpos_51.inputs["Offset"])
    prim_53 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_53.location = (0, 4800)
    prim_53.label = 'column4'
    val_54 = node_tree.nodes.new("ShaderNodeValue")
    val_54.location = (180, 4800)
    val_54.label = 'column4 radius'
    val_54.outputs[0].default_value = 4.925
    val_55 = node_tree.nodes.new("ShaderNodeValue")
    val_55.location = (360, 4800)
    val_55.label = 'column4 depth'
    val_55.outputs[0].default_value = 10
    node_tree.links.new(val_54.outputs["Value"], prim_53.inputs["Radius"])
    node_tree.links.new(val_55.outputs["Value"], prim_53.inputs["Depth"])
    prim_53.inputs["Vertices"].default_value = 32
    setpos_56 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_56.location = (0, 5000)
    setpos_56.label = 'column4 position'
    node_tree.links.new(prim_53.outputs["Mesh"], setpos_56.inputs["Geometry"])
    vec_57 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_57.location = (180, 5000)
    vec_57.label = 'column4 position offset'
    vec_57.vector = [-30, -30, 2]
    node_tree.links.new(vec_57.outputs["Vector"], setpos_56.inputs["Offset"])
    bool_58 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_58.location = (0, 5200)
    bool_58.label = 'difference'
    bool_58.operation = "DIFFERENCE"
    bool_58.solver = "EXACT"
    node_tree.links.new(bool_37.outputs["Mesh"], bool_58.inputs[0])
    node_tree.links.new(setpos_41.outputs["Geometry"], bool_58.inputs[1])
    node_tree.links.new(setpos_46.outputs["Geometry"], bool_58.inputs[1])
    node_tree.links.new(setpos_51.outputs["Geometry"], bool_58.inputs[1])
    node_tree.links.new(setpos_56.outputs["Geometry"], bool_58.inputs[1])
    xform_59 = node_tree.nodes.new("GeometryNodeTransform")
    xform_59.location = (0, 5400)
    xform_59.label = 'difference translate'
    node_tree.links.new(bool_58.outputs["Mesh"], xform_59.inputs["Geometry"])
    vec_60 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_60.location = (180, 5400)
    vec_60.label = 'difference translate translation'
    vec_60.vector = [0, 0, 40]
    node_tree.links.new(vec_60.outputs["Vector"], xform_59.inputs["Translation"])
    out_61 = node_tree.nodes.new("NodeGroupOutput")
    out_61.location = (0, 5600)
    out_61.label = "output"
    node_tree.links.new(xform_59.outputs[0], out_61.inputs[0])

    return node_tree


# Execute
setup()

