import bpy


def setup(object_name='create_cam_tripod_support'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'base'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "base size"
    vec_2.vector = [60, 10, 20]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'base position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'base position offset'
    vec_4.vector = [0, 30, 0]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_5.location = (0, 600)
    prim_5.label = 'column1'
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (180, 600)
    val_6.label = 'column1 radius'
    val_6.outputs[0].default_value = 6.925
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (360, 600)
    val_7.label = 'column1 depth'
    val_7.outputs[0].default_value = 20
    node_tree.links.new(val_6.outputs["Value"], prim_5.inputs["Radius"])
    node_tree.links.new(val_7.outputs["Value"], prim_5.inputs["Depth"])
    prim_5.inputs["Vertices"].default_value = 32
    setpos_8 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_8.location = (0, 800)
    setpos_8.label = 'column1 position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_8.inputs["Geometry"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (180, 800)
    vec_9.label = 'column1 position offset'
    vec_9.vector = [30, 30, 0]
    node_tree.links.new(vec_9.outputs["Vector"], setpos_8.inputs["Offset"])
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_10.location = (0, 1000)
    prim_10.label = 'column2'
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (180, 1000)
    val_11.label = 'column2 radius'
    val_11.outputs[0].default_value = 6.925
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (360, 1000)
    val_12.label = 'column2 depth'
    val_12.outputs[0].default_value = 20
    node_tree.links.new(val_11.outputs["Value"], prim_10.inputs["Radius"])
    node_tree.links.new(val_12.outputs["Value"], prim_10.inputs["Depth"])
    prim_10.inputs["Vertices"].default_value = 32
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1200)
    setpos_13.label = 'column2 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = 'column2 position offset'
    vec_14.vector = [-30, 30, 0]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    bool_15 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_15.location = (0, 1400)
    bool_15.label = 'union'
    bool_15.operation = "UNION"
    bool_15.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_15.inputs[1])
    node_tree.links.new(setpos_8.outputs["Geometry"], bool_15.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_15.inputs[1])
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (0, 1600)
    prim_16.label = 'column1'
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (180, 1600)
    val_17.label = 'column1 radius'
    val_17.outputs[0].default_value = 5.05
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (360, 1600)
    val_18.label = 'column1 depth'
    val_18.outputs[0].default_value = 35
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    setpos_19 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_19.location = (0, 1800)
    setpos_19.label = 'column1 position'
    node_tree.links.new(prim_16.outputs["Mesh"], setpos_19.inputs["Geometry"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (180, 1800)
    vec_20.label = 'column1 position offset'
    vec_20.vector = [30, 30, 0]
    node_tree.links.new(vec_20.outputs["Vector"], setpos_19.inputs["Offset"])
    prim_21 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_21.location = (0, 2000)
    prim_21.label = 'column2'
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (180, 2000)
    val_22.label = 'column2 radius'
    val_22.outputs[0].default_value = 5.05
    val_23 = node_tree.nodes.new("ShaderNodeValue")
    val_23.location = (360, 2000)
    val_23.label = 'column2 depth'
    val_23.outputs[0].default_value = 35
    node_tree.links.new(val_22.outputs["Value"], prim_21.inputs["Radius"])
    node_tree.links.new(val_23.outputs["Value"], prim_21.inputs["Depth"])
    prim_21.inputs["Vertices"].default_value = 32
    setpos_24 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_24.location = (0, 2200)
    setpos_24.label = 'column2 position'
    node_tree.links.new(prim_21.outputs["Mesh"], setpos_24.inputs["Geometry"])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (180, 2200)
    vec_25.label = 'column2 position offset'
    vec_25.vector = [-30, 30, 0]
    node_tree.links.new(vec_25.outputs["Vector"], setpos_24.inputs["Offset"])
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (0, 2400)
    prim_26.label = 'h_screw'
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (180, 2400)
    val_27.label = 'h_screw radius'
    val_27.outputs[0].default_value = 4
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (360, 2400)
    val_28.label = 'h_screw depth'
    val_28.outputs[0].default_value = 30
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    xform_29 = node_tree.nodes.new("GeometryNodeTransform")
    xform_29.location = (0, 2600)
    xform_29.label = 'h_screw rotate'
    node_tree.links.new(prim_26.outputs["Mesh"], xform_29.inputs["Geometry"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2600)
    vec_30.label = 'h_screw rotate rotation'
    vec_30.vector = [0.0, 1.5707963267948966, 1.5707963267948966]
    node_tree.links.new(vec_30.outputs["Vector"], xform_29.inputs["Rotation"])
    setpos_31 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_31.location = (0, 2800)
    setpos_31.label = 'h_screw rotate position'
    node_tree.links.new(xform_29.outputs["Geometry"], setpos_31.inputs["Geometry"])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (180, 2800)
    vec_32.label = 'h_screw rotate position offset'
    vec_32.vector = [0, 30, 0]
    node_tree.links.new(vec_32.outputs["Vector"], setpos_31.inputs["Offset"])
    bool_33 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_33.location = (0, 3000)
    bool_33.label = 'difference'
    bool_33.operation = "DIFFERENCE"
    bool_33.solver = "EXACT"
    node_tree.links.new(bool_15.outputs["Mesh"], bool_33.inputs[0])
    node_tree.links.new(setpos_19.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_24.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_31.outputs["Geometry"], bool_33.inputs[1])
    xform_34 = node_tree.nodes.new("GeometryNodeTransform")
    xform_34.location = (0, 3200)
    xform_34.label = 'difference translate'
    node_tree.links.new(bool_33.outputs["Mesh"], xform_34.inputs["Geometry"])
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (180, 3200)
    vec_35.label = 'difference translate translation'
    vec_35.vector = [0, 0, 40]
    node_tree.links.new(vec_35.outputs["Vector"], xform_34.inputs["Translation"])
    out_36 = node_tree.nodes.new("NodeGroupOutput")
    out_36.location = (0, 3400)
    out_36.label = "output"
    node_tree.links.new(xform_34.outputs[0], out_36.inputs[0])

    return node_tree


# Execute
setup()

