import bpy


def setup(object_name='dummy_stepper'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'stepper'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'stepper radius'
    val_2.outputs[0].default_value = 14
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'stepper depth'
    val_3.outputs[0].default_value = 19
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_4.location = (0, 400)
    prim_4.label = 'wires'
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = "wires size"
    vec_5.vector = [19, 10, 19]
    node_tree.links.new(vec_5.outputs["Vector"], prim_4.inputs["Size"])
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (0, 600)
    setpos_6.label = 'wires position'
    node_tree.links.new(prim_4.outputs["Mesh"], setpos_6.inputs["Geometry"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (180, 600)
    vec_7.label = 'wires position offset'
    vec_7.vector = [0, -10, 0]
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (0, 800)
    prim_8.label = 'connector'
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (180, 800)
    val_9.label = 'connector radius'
    val_9.outputs[0].default_value = 2.9
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (360, 800)
    val_10.label = 'connector depth'
    val_10.outputs[0].default_value = 10
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 32
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (0, 1000)
    setpos_11.label = 'connector position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_11.inputs["Geometry"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (180, 1000)
    vec_12.label = 'connector position offset'
    vec_12.vector = [0, 0, 14.5]
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_13.location = (0, 1200)
    prim_13.label = 'connector'
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = "connector size"
    vec_14.vector = [6, 3.8, 10]
    node_tree.links.new(vec_14.outputs["Vector"], prim_13.inputs["Size"])
    setpos_15 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_15.location = (0, 1400)
    setpos_15.label = 'connector position'
    node_tree.links.new(prim_13.outputs["Mesh"], setpos_15.inputs["Geometry"])
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (180, 1400)
    vec_16.label = 'connector position offset'
    vec_16.vector = [0, 0, 14.5]
    node_tree.links.new(vec_16.outputs["Vector"], setpos_15.inputs["Offset"])
    bool_17 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_17.location = (0, 1600)
    bool_17.label = 'intersect'
    bool_17.operation = "INTERSECT"
    bool_17.solver = "EXACT"
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_17.inputs[1])
    node_tree.links.new(setpos_15.outputs["Geometry"], bool_17.inputs[1])
    xform_18 = node_tree.nodes.new("GeometryNodeTransform")
    xform_18.location = (0, 1800)
    xform_18.label = 'intersect translate'
    node_tree.links.new(bool_17.outputs["Mesh"], xform_18.inputs["Geometry"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (180, 1800)
    vec_19.label = 'intersect translate translation'
    vec_19.vector = [0, 8, 0]
    node_tree.links.new(vec_19.outputs["Vector"], xform_18.inputs["Translation"])
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_20.location = (0, 2000)
    prim_20.label = 'screws_base'
    vec_21 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_21.location = (180, 2000)
    vec_21.label = "screws_base size"
    vec_21.vector = [35, 4, 1]
    node_tree.links.new(vec_21.outputs["Vector"], prim_20.inputs["Size"])
    setpos_22 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_22.location = (0, 2200)
    setpos_22.label = 'screws_base position'
    node_tree.links.new(prim_20.outputs["Mesh"], setpos_22.inputs["Geometry"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (180, 2200)
    vec_23.label = 'screws_base position offset'
    vec_23.vector = [0, 0, 9.0]
    node_tree.links.new(vec_23.outputs["Vector"], setpos_22.inputs["Offset"])
    bool_24 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_24.location = (0, 2400)
    bool_24.label = 'union'
    bool_24.operation = "UNION"
    bool_24.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_24.inputs[1])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_24.inputs[1])
    node_tree.links.new(xform_18.outputs["Geometry"], bool_24.inputs[1])
    node_tree.links.new(setpos_22.outputs["Geometry"], bool_24.inputs[1])
    xform_25 = node_tree.nodes.new("GeometryNodeTransform")
    xform_25.location = (0, 2600)
    xform_25.label = 'union rotate'
    node_tree.links.new(bool_24.outputs["Mesh"], xform_25.inputs["Geometry"])
    vec_26 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_26.location = (180, 2600)
    vec_26.label = 'union rotate rotation'
    vec_26.vector = [0.0, 0.0, 3.141592653589793]
    node_tree.links.new(vec_26.outputs["Vector"], xform_25.inputs["Rotation"])
    xform_27 = node_tree.nodes.new("GeometryNodeTransform")
    xform_27.location = (0, 2800)
    xform_27.label = 'union rotate translate'
    node_tree.links.new(xform_25.outputs["Geometry"], xform_27.inputs["Geometry"])
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (180, 2800)
    vec_28.label = 'union rotate translate translation'
    vec_28.vector = [0, 40, -11]
    node_tree.links.new(vec_28.outputs["Vector"], xform_27.inputs["Translation"])
    out_29 = node_tree.nodes.new("NodeGroupOutput")
    out_29.location = (0, 3000)
    out_29.label = "output"
    node_tree.links.new(xform_27.outputs[0], out_29.inputs[0])

    return node_tree


# Execute
setup()

