import bpy


def setup(object_name='film_slider_2'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'slider'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "slider size"
    vec_2.vector = [45, 45, 5]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'slider position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'slider position offset'
    vec_4.vector = [0, 0, -5]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (0, 600)
    prim_5.label = 'h_slider'
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (180, 600)
    vec_6.label = "h_slider size"
    vec_6.vector = [40, 34.5, 30]
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (0, 800)
    prim_7.label = 'join_1'
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (180, 800)
    vec_8.label = "join_1 size"
    vec_8.vector = [40.125, 3.125, 3.125]
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 1000)
    setpos_9.label = 'join_1 position'
    node_tree.links.new(prim_7.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 1000)
    vec_10.label = 'join_1 position offset'
    vec_10.vector = [0, 20, -4]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_11.location = (0, 1200)
    prim_11.label = 'join_1'
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (180, 1200)
    vec_12.label = "join_1 size"
    vec_12.vector = [40.125, 3.125, 3.125]
    node_tree.links.new(vec_12.outputs["Vector"], prim_11.inputs["Size"])
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1400)
    setpos_13.label = 'join_1 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1400)
    vec_14.label = 'join_1 position offset'
    vec_14.vector = [0, -20, -4]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    bool_15 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_15.location = (0, 1600)
    bool_15.label = 'difference'
    bool_15.operation = "DIFFERENCE"
    bool_15.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_15.inputs[0])
    node_tree.links.new(prim_5.outputs["Mesh"], bool_15.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_15.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_15.inputs[1])
    out_16 = node_tree.nodes.new("NodeGroupOutput")
    out_16.location = (0, 1800)
    out_16.label = "output"
    node_tree.links.new(bool_15.outputs[0], out_16.inputs[0])

    return node_tree


# Execute
setup()

