import bpy


def setup(object_name='film'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'film_35mm'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "film_35mm size"
    vec_2.vector = [230, 41, 7]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_3.location = (0, 400)
    prim_3.label = 'h_magnet_1'
    val_4 = node_tree.nodes.new("ShaderNodeValue")
    val_4.location = (180, 400)
    val_4.label = 'h_magnet_1 radius'
    val_4.outputs[0].default_value = 2.625
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (360, 400)
    val_5.label = 'h_magnet_1 depth'
    val_5.outputs[0].default_value = 3
    node_tree.links.new(val_4.outputs["Value"], prim_3.inputs["Radius"])
    node_tree.links.new(val_5.outputs["Value"], prim_3.inputs["Depth"])
    prim_3.inputs["Vertices"].default_value = 32
    setpos_6 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_6.location = (0, 600)
    setpos_6.label = 'h_magnet_1 position'
    node_tree.links.new(prim_3.outputs["Mesh"], setpos_6.inputs["Geometry"])
    vec_7 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_7.location = (180, 600)
    vec_7.label = 'h_magnet_1 position offset'
    vec_7.vector = [110.0, 0, 0.5]
    node_tree.links.new(vec_7.outputs["Vector"], setpos_6.inputs["Offset"])
    prim_8 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_8.location = (0, 800)
    prim_8.label = 'h_magnet_2'
    val_9 = node_tree.nodes.new("ShaderNodeValue")
    val_9.location = (180, 800)
    val_9.label = 'h_magnet_2 radius'
    val_9.outputs[0].default_value = 2.625
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (360, 800)
    val_10.label = 'h_magnet_2 depth'
    val_10.outputs[0].default_value = 3
    node_tree.links.new(val_9.outputs["Value"], prim_8.inputs["Radius"])
    node_tree.links.new(val_10.outputs["Value"], prim_8.inputs["Depth"])
    prim_8.inputs["Vertices"].default_value = 32
    setpos_11 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_11.location = (0, 1000)
    setpos_11.label = 'h_magnet_2 position'
    node_tree.links.new(prim_8.outputs["Mesh"], setpos_11.inputs["Geometry"])
    vec_12 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_12.location = (180, 1000)
    vec_12.label = 'h_magnet_2 position offset'
    vec_12.vector = [110.0, 10, 0.5]
    node_tree.links.new(vec_12.outputs["Vector"], setpos_11.inputs["Offset"])
    prim_13 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_13.location = (0, 1200)
    prim_13.label = 'h_magnet_3'
    val_14 = node_tree.nodes.new("ShaderNodeValue")
    val_14.location = (180, 1200)
    val_14.label = 'h_magnet_3 radius'
    val_14.outputs[0].default_value = 2.625
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (360, 1200)
    val_15.label = 'h_magnet_3 depth'
    val_15.outputs[0].default_value = 3
    node_tree.links.new(val_14.outputs["Value"], prim_13.inputs["Radius"])
    node_tree.links.new(val_15.outputs["Value"], prim_13.inputs["Depth"])
    prim_13.inputs["Vertices"].default_value = 32
    setpos_16 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_16.location = (0, 1400)
    setpos_16.label = 'h_magnet_3 position'
    node_tree.links.new(prim_13.outputs["Mesh"], setpos_16.inputs["Geometry"])
    vec_17 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_17.location = (180, 1400)
    vec_17.label = 'h_magnet_3 position offset'
    vec_17.vector = [110.0, -10, 0.5]
    node_tree.links.new(vec_17.outputs["Vector"], setpos_16.inputs["Offset"])
    prim_18 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_18.location = (0, 1600)
    prim_18.label = 'h_magnet_5'
    val_19 = node_tree.nodes.new("ShaderNodeValue")
    val_19.location = (180, 1600)
    val_19.label = 'h_magnet_5 radius'
    val_19.outputs[0].default_value = 2.625
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (360, 1600)
    val_20.label = 'h_magnet_5 depth'
    val_20.outputs[0].default_value = 3
    node_tree.links.new(val_19.outputs["Value"], prim_18.inputs["Radius"])
    node_tree.links.new(val_20.outputs["Value"], prim_18.inputs["Depth"])
    prim_18.inputs["Vertices"].default_value = 32
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (0, 1800)
    setpos_21.label = 'h_magnet_5 position'
    node_tree.links.new(prim_18.outputs["Mesh"], setpos_21.inputs["Geometry"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (180, 1800)
    vec_22.label = 'h_magnet_5 position offset'
    vec_22.vector = [-110.0, 0, 0.5]
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (0, 2000)
    prim_23.label = 'h_magnet_6'
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (180, 2000)
    val_24.label = 'h_magnet_6 radius'
    val_24.outputs[0].default_value = 2.625
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (360, 2000)
    val_25.label = 'h_magnet_6 depth'
    val_25.outputs[0].default_value = 3
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    setpos_26 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_26.location = (0, 2200)
    setpos_26.label = 'h_magnet_6 position'
    node_tree.links.new(prim_23.outputs["Mesh"], setpos_26.inputs["Geometry"])
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (180, 2200)
    vec_27.label = 'h_magnet_6 position offset'
    vec_27.vector = [-110.0, 10, 0.5]
    node_tree.links.new(vec_27.outputs["Vector"], setpos_26.inputs["Offset"])
    prim_28 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_28.location = (0, 2400)
    prim_28.label = 'h_magnet_7'
    val_29 = node_tree.nodes.new("ShaderNodeValue")
    val_29.location = (180, 2400)
    val_29.label = 'h_magnet_7 radius'
    val_29.outputs[0].default_value = 2.625
    val_30 = node_tree.nodes.new("ShaderNodeValue")
    val_30.location = (360, 2400)
    val_30.label = 'h_magnet_7 depth'
    val_30.outputs[0].default_value = 3
    node_tree.links.new(val_29.outputs["Value"], prim_28.inputs["Radius"])
    node_tree.links.new(val_30.outputs["Value"], prim_28.inputs["Depth"])
    prim_28.inputs["Vertices"].default_value = 32
    setpos_31 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_31.location = (0, 2600)
    setpos_31.label = 'h_magnet_7 position'
    node_tree.links.new(prim_28.outputs["Mesh"], setpos_31.inputs["Geometry"])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (180, 2600)
    vec_32.label = 'h_magnet_7 position offset'
    vec_32.vector = [-110.0, -10, 0.5]
    node_tree.links.new(vec_32.outputs["Vector"], setpos_31.inputs["Offset"])
    prim_33 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_33.location = (0, 2800)
    prim_33.label = 'h_film'
    vec_34 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_34.location = (180, 2800)
    vec_34.label = "h_film size"
    vec_34.vector = [210, 30, 7]
    node_tree.links.new(vec_34.outputs["Vector"], prim_33.inputs["Size"])
    bool_35 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_35.location = (0, 3000)
    bool_35.label = 'difference'
    bool_35.operation = "DIFFERENCE"
    bool_35.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_35.inputs[0])
    node_tree.links.new(setpos_6.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_11.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_16.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_26.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(setpos_31.outputs["Geometry"], bool_35.inputs[1])
    node_tree.links.new(prim_33.outputs["Mesh"], bool_35.inputs[1])
    xform_36 = node_tree.nodes.new("GeometryNodeTransform")
    xform_36.location = (0, 3200)
    xform_36.label = 'difference translate'
    node_tree.links.new(bool_35.outputs["Mesh"], xform_36.inputs["Geometry"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (180, 3200)
    vec_37.label = 'difference translate translation'
    vec_37.vector = [0, 0, 10]
    node_tree.links.new(vec_37.outputs["Vector"], xform_36.inputs["Translation"])
    out_38 = node_tree.nodes.new("NodeGroupOutput")
    out_38.location = (0, 3400)
    out_38.label = "output"
    node_tree.links.new(xform_36.outputs[0], out_38.inputs[0])

    return node_tree


# Execute
setup()

