import bpy


def setup(object_name='film_slider'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'slider_base'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "slider_base size"
    vec_2.vector = [80, 80, 5]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_3.location = (0, 400)
    prim_3.label = 'h_slider'
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = "h_slider size"
    vec_4.vector = [40, 34.5, 30]
    node_tree.links.new(vec_4.outputs["Vector"], prim_3.inputs["Size"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_5.location = (0, 600)
    prim_5.label = 'h_slider'
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (180, 600)
    vec_6.label = "h_slider size"
    vec_6.vector = [160, 35.125, 0.5]
    node_tree.links.new(vec_6.outputs["Vector"], prim_5.inputs["Size"])
    setpos_7 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_7.location = (0, 800)
    setpos_7.label = 'h_slider position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_7.inputs["Geometry"])
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (180, 800)
    vec_8.label = 'h_slider position offset'
    vec_8.vector = [0, 0, -2.25]
    node_tree.links.new(vec_8.outputs["Vector"], setpos_7.inputs["Offset"])
    prim_9 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_9.location = (0, 1000)
    prim_9.label = 'column1'
    val_10 = node_tree.nodes.new("ShaderNodeValue")
    val_10.location = (180, 1000)
    val_10.label = 'column1 radius'
    val_10.outputs[0].default_value = 5.05
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (360, 1000)
    val_11.label = 'column1 depth'
    val_11.outputs[0].default_value = 20
    node_tree.links.new(val_10.outputs["Value"], prim_9.inputs["Radius"])
    node_tree.links.new(val_11.outputs["Value"], prim_9.inputs["Depth"])
    prim_9.inputs["Vertices"].default_value = 32
    setpos_12 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_12.location = (0, 1200)
    setpos_12.label = 'column1 position'
    node_tree.links.new(prim_9.outputs["Mesh"], setpos_12.inputs["Geometry"])
    vec_13 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_13.location = (180, 1200)
    vec_13.label = 'column1 position offset'
    vec_13.vector = [30, 30, 2]
    node_tree.links.new(vec_13.outputs["Vector"], setpos_12.inputs["Offset"])
    prim_14 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_14.location = (0, 1400)
    prim_14.label = 'column2'
    val_15 = node_tree.nodes.new("ShaderNodeValue")
    val_15.location = (180, 1400)
    val_15.label = 'column2 radius'
    val_15.outputs[0].default_value = 5.05
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (360, 1400)
    val_16.label = 'column2 depth'
    val_16.outputs[0].default_value = 20
    node_tree.links.new(val_15.outputs["Value"], prim_14.inputs["Radius"])
    node_tree.links.new(val_16.outputs["Value"], prim_14.inputs["Depth"])
    prim_14.inputs["Vertices"].default_value = 32
    setpos_17 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_17.location = (0, 1600)
    setpos_17.label = 'column2 position'
    node_tree.links.new(prim_14.outputs["Mesh"], setpos_17.inputs["Geometry"])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (180, 1600)
    vec_18.label = 'column2 position offset'
    vec_18.vector = [-30, 30, 2]
    node_tree.links.new(vec_18.outputs["Vector"], setpos_17.inputs["Offset"])
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_19.location = (0, 1800)
    prim_19.label = 'column3'
    val_20 = node_tree.nodes.new("ShaderNodeValue")
    val_20.location = (180, 1800)
    val_20.label = 'column3 radius'
    val_20.outputs[0].default_value = 5.05
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (360, 1800)
    val_21.label = 'column3 depth'
    val_21.outputs[0].default_value = 20
    node_tree.links.new(val_20.outputs["Value"], prim_19.inputs["Radius"])
    node_tree.links.new(val_21.outputs["Value"], prim_19.inputs["Depth"])
    prim_19.inputs["Vertices"].default_value = 32
    setpos_22 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_22.location = (0, 2000)
    setpos_22.label = 'column3 position'
    node_tree.links.new(prim_19.outputs["Mesh"], setpos_22.inputs["Geometry"])
    vec_23 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_23.location = (180, 2000)
    vec_23.label = 'column3 position offset'
    vec_23.vector = [30, -30, 2]
    node_tree.links.new(vec_23.outputs["Vector"], setpos_22.inputs["Offset"])
    prim_24 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_24.location = (0, 2200)
    prim_24.label = 'column4'
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (180, 2200)
    val_25.label = 'column4 radius'
    val_25.outputs[0].default_value = 5.05
    val_26 = node_tree.nodes.new("ShaderNodeValue")
    val_26.location = (360, 2200)
    val_26.label = 'column4 depth'
    val_26.outputs[0].default_value = 20
    node_tree.links.new(val_25.outputs["Value"], prim_24.inputs["Radius"])
    node_tree.links.new(val_26.outputs["Value"], prim_24.inputs["Depth"])
    prim_24.inputs["Vertices"].default_value = 32
    setpos_27 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_27.location = (0, 2400)
    setpos_27.label = 'column4 position'
    node_tree.links.new(prim_24.outputs["Mesh"], setpos_27.inputs["Geometry"])
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (180, 2400)
    vec_28.label = 'column4 position offset'
    vec_28.vector = [-30, -30, 2]
    node_tree.links.new(vec_28.outputs["Vector"], setpos_27.inputs["Offset"])
    bool_29 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_29.location = (0, 2600)
    bool_29.label = 'difference'
    bool_29.operation = "DIFFERENCE"
    bool_29.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_29.inputs[0])
    node_tree.links.new(prim_3.outputs["Mesh"], bool_29.inputs[1])
    node_tree.links.new(setpos_7.outputs["Geometry"], bool_29.inputs[1])
    node_tree.links.new(setpos_12.outputs["Geometry"], bool_29.inputs[1])
    node_tree.links.new(setpos_17.outputs["Geometry"], bool_29.inputs[1])
    node_tree.links.new(setpos_22.outputs["Geometry"], bool_29.inputs[1])
    node_tree.links.new(setpos_27.outputs["Geometry"], bool_29.inputs[1])
    prim_30 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_30.location = (0, 2800)
    prim_30.label = 'join_1'
    vec_31 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_31.location = (180, 2800)
    vec_31.label = "join_1 size"
    vec_31.vector = [40, 3, 3]
    node_tree.links.new(vec_31.outputs["Vector"], prim_30.inputs["Size"])
    setpos_32 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_32.location = (0, 3000)
    setpos_32.label = 'join_1 position'
    node_tree.links.new(prim_30.outputs["Mesh"], setpos_32.inputs["Geometry"])
    vec_33 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_33.location = (180, 3000)
    vec_33.label = 'join_1 position offset'
    vec_33.vector = [0, 20, -4]
    node_tree.links.new(vec_33.outputs["Vector"], setpos_32.inputs["Offset"])
    prim_34 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_34.location = (0, 3200)
    prim_34.label = 'join_1'
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (180, 3200)
    vec_35.label = "join_1 size"
    vec_35.vector = [40, 3, 3]
    node_tree.links.new(vec_35.outputs["Vector"], prim_34.inputs["Size"])
    setpos_36 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_36.location = (0, 3400)
    setpos_36.label = 'join_1 position'
    node_tree.links.new(prim_34.outputs["Mesh"], setpos_36.inputs["Geometry"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (180, 3400)
    vec_37.label = 'join_1 position offset'
    vec_37.vector = [0, -20, -4]
    node_tree.links.new(vec_37.outputs["Vector"], setpos_36.inputs["Offset"])
    bool_38 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_38.location = (0, 3600)
    bool_38.label = 'union'
    bool_38.operation = "UNION"
    bool_38.solver = "EXACT"
    node_tree.links.new(bool_29.outputs["Mesh"], bool_38.inputs[1])
    node_tree.links.new(setpos_32.outputs["Geometry"], bool_38.inputs[1])
    node_tree.links.new(setpos_36.outputs["Geometry"], bool_38.inputs[1])
    out_39 = node_tree.nodes.new("NodeGroupOutput")
    out_39.location = (0, 3800)
    out_39.label = "output"
    node_tree.links.new(bool_38.outputs[0], out_39.inputs[0])

    return node_tree


# Execute
setup()

