import bpy


def setup(object_name='film_support'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'film_support'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "film_support size"
    vec_2.vector = [100, 60, 4]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'film_support position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'film_support position offset'
    vec_4.vector = [0, 0, 15]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_5.location = (0, 600)
    prim_5.label = 'column1'
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (180, 600)
    val_6.label = 'column1 radius'
    val_6.outputs[0].default_value = 6.925
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (360, 600)
    val_7.label = 'column1 depth'
    val_7.outputs[0].default_value = 13
    node_tree.links.new(val_6.outputs["Value"], prim_5.inputs["Radius"])
    node_tree.links.new(val_7.outputs["Value"], prim_5.inputs["Depth"])
    prim_5.inputs["Vertices"].default_value = 32
    setpos_8 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_8.location = (0, 800)
    setpos_8.label = 'column1 position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_8.inputs["Geometry"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (180, 800)
    vec_9.label = 'column1 position offset'
    vec_9.vector = [30, 30, 10.5]
    node_tree.links.new(vec_9.outputs["Vector"], setpos_8.inputs["Offset"])
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_10.location = (0, 1000)
    prim_10.label = 'column2'
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (180, 1000)
    val_11.label = 'column2 radius'
    val_11.outputs[0].default_value = 6.925
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (360, 1000)
    val_12.label = 'column2 depth'
    val_12.outputs[0].default_value = 13
    node_tree.links.new(val_11.outputs["Value"], prim_10.inputs["Radius"])
    node_tree.links.new(val_12.outputs["Value"], prim_10.inputs["Depth"])
    prim_10.inputs["Vertices"].default_value = 32
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1200)
    setpos_13.label = 'column2 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = 'column2 position offset'
    vec_14.vector = [-30, 30, 10.5]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_15.location = (0, 1400)
    prim_15.label = 'column3'
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (180, 1400)
    val_16.label = 'column3 radius'
    val_16.outputs[0].default_value = 6.925
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (360, 1400)
    val_17.label = 'column3 depth'
    val_17.outputs[0].default_value = 13
    node_tree.links.new(val_16.outputs["Value"], prim_15.inputs["Radius"])
    node_tree.links.new(val_17.outputs["Value"], prim_15.inputs["Depth"])
    prim_15.inputs["Vertices"].default_value = 32
    setpos_18 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_18.location = (0, 1600)
    setpos_18.label = 'column3 position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_18.inputs["Geometry"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (180, 1600)
    vec_19.label = 'column3 position offset'
    vec_19.vector = [30, -30, 10.5]
    node_tree.links.new(vec_19.outputs["Vector"], setpos_18.inputs["Offset"])
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_20.location = (0, 1800)
    prim_20.label = 'column4'
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (180, 1800)
    val_21.label = 'column4 radius'
    val_21.outputs[0].default_value = 6.925
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (360, 1800)
    val_22.label = 'column4 depth'
    val_22.outputs[0].default_value = 13
    node_tree.links.new(val_21.outputs["Value"], prim_20.inputs["Radius"])
    node_tree.links.new(val_22.outputs["Value"], prim_20.inputs["Depth"])
    prim_20.inputs["Vertices"].default_value = 32
    setpos_23 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_23.location = (0, 2000)
    setpos_23.label = 'column4 position'
    node_tree.links.new(prim_20.outputs["Mesh"], setpos_23.inputs["Geometry"])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (180, 2000)
    vec_24.label = 'column4 position offset'
    vec_24.vector = [-30, -30, 10.5]
    node_tree.links.new(vec_24.outputs["Vector"], setpos_23.inputs["Offset"])
    prim_25 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_25.location = (0, 2200)
    prim_25.label = 'film_35mm'
    vec_26 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_26.location = (180, 2200)
    vec_26.label = "film_35mm size"
    vec_26.vector = [100, 60, 10]
    node_tree.links.new(vec_26.outputs["Vector"], prim_25.inputs["Size"])
    setpos_27 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_27.location = (0, 2400)
    setpos_27.label = 'film_35mm position'
    node_tree.links.new(prim_25.outputs["Mesh"], setpos_27.inputs["Geometry"])
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (180, 2400)
    vec_28.label = 'film_35mm position offset'
    vec_28.vector = [0, 0, 9]
    node_tree.links.new(vec_28.outputs["Vector"], setpos_27.inputs["Offset"])
    prim_29 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_29.location = (0, 2600)
    prim_29.label = 'h_film_35mm'
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2600)
    vec_30.label = "h_film_35mm size"
    vec_30.vector = [120, 46.5, 10]
    node_tree.links.new(vec_30.outputs["Vector"], prim_29.inputs["Size"])
    setpos_31 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_31.location = (0, 2800)
    setpos_31.label = 'h_film_35mm position'
    node_tree.links.new(prim_29.outputs["Mesh"], setpos_31.inputs["Geometry"])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (180, 2800)
    vec_32.label = 'h_film_35mm position offset'
    vec_32.vector = [0, 0, 9]
    node_tree.links.new(vec_32.outputs["Vector"], setpos_31.inputs["Offset"])
    bool_33 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_33.location = (0, 3000)
    bool_33.label = 'difference'
    bool_33.operation = "DIFFERENCE"
    bool_33.solver = "EXACT"
    node_tree.links.new(setpos_27.outputs["Geometry"], bool_33.inputs[0])
    node_tree.links.new(setpos_31.outputs["Geometry"], bool_33.inputs[1])
    prim_34 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_34.location = (0, 3200)
    prim_34.label = 'film_tab'
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (180, 3200)
    vec_35.label = "film_tab size"
    vec_35.vector = [100, 7, 1]
    node_tree.links.new(vec_35.outputs["Vector"], prim_34.inputs["Size"])
    setpos_36 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_36.location = (0, 3400)
    setpos_36.label = 'film_tab position'
    node_tree.links.new(prim_34.outputs["Mesh"], setpos_36.inputs["Geometry"])
    vec_37 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_37.location = (180, 3400)
    vec_37.label = 'film_tab position offset'
    vec_37.vector = [0, 20, 4.5]
    node_tree.links.new(vec_37.outputs["Vector"], setpos_36.inputs["Offset"])
    prim_38 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_38.location = (0, 3600)
    prim_38.label = 'film_tab'
    vec_39 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_39.location = (180, 3600)
    vec_39.label = "film_tab size"
    vec_39.vector = [100, 7, 1]
    node_tree.links.new(vec_39.outputs["Vector"], prim_38.inputs["Size"])
    setpos_40 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_40.location = (0, 3800)
    setpos_40.label = 'film_tab position'
    node_tree.links.new(prim_38.outputs["Mesh"], setpos_40.inputs["Geometry"])
    vec_41 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_41.location = (180, 3800)
    vec_41.label = 'film_tab position offset'
    vec_41.vector = [0, -20, 4.5]
    node_tree.links.new(vec_41.outputs["Vector"], setpos_40.inputs["Offset"])
    bool_42 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_42.location = (0, 4000)
    bool_42.label = 'union'
    bool_42.operation = "UNION"
    bool_42.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(setpos_8.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(setpos_18.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(setpos_23.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(bool_33.outputs["Mesh"], bool_42.inputs[1])
    node_tree.links.new(setpos_36.outputs["Geometry"], bool_42.inputs[1])
    node_tree.links.new(setpos_40.outputs["Geometry"], bool_42.inputs[1])
    prim_43 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_43.location = (0, 4200)
    prim_43.label = 'column1'
    val_44 = node_tree.nodes.new("ShaderNodeValue")
    val_44.location = (180, 4200)
    val_44.label = 'column1 radius'
    val_44.outputs[0].default_value = 5.175
    val_45 = node_tree.nodes.new("ShaderNodeValue")
    val_45.location = (360, 4200)
    val_45.label = 'column1 depth'
    val_45.outputs[0].default_value = 50
    node_tree.links.new(val_44.outputs["Value"], prim_43.inputs["Radius"])
    node_tree.links.new(val_45.outputs["Value"], prim_43.inputs["Depth"])
    prim_43.inputs["Vertices"].default_value = 32
    setpos_46 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_46.location = (0, 4400)
    setpos_46.label = 'column1 position'
    node_tree.links.new(prim_43.outputs["Mesh"], setpos_46.inputs["Geometry"])
    vec_47 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_47.location = (180, 4400)
    vec_47.label = 'column1 position offset'
    vec_47.vector = [30, 30, 0]
    node_tree.links.new(vec_47.outputs["Vector"], setpos_46.inputs["Offset"])
    prim_48 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_48.location = (0, 4600)
    prim_48.label = 'column2'
    val_49 = node_tree.nodes.new("ShaderNodeValue")
    val_49.location = (180, 4600)
    val_49.label = 'column2 radius'
    val_49.outputs[0].default_value = 5.175
    val_50 = node_tree.nodes.new("ShaderNodeValue")
    val_50.location = (360, 4600)
    val_50.label = 'column2 depth'
    val_50.outputs[0].default_value = 50
    node_tree.links.new(val_49.outputs["Value"], prim_48.inputs["Radius"])
    node_tree.links.new(val_50.outputs["Value"], prim_48.inputs["Depth"])
    prim_48.inputs["Vertices"].default_value = 32
    setpos_51 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_51.location = (0, 4800)
    setpos_51.label = 'column2 position'
    node_tree.links.new(prim_48.outputs["Mesh"], setpos_51.inputs["Geometry"])
    vec_52 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_52.location = (180, 4800)
    vec_52.label = 'column2 position offset'
    vec_52.vector = [-30, 30, 0]
    node_tree.links.new(vec_52.outputs["Vector"], setpos_51.inputs["Offset"])
    prim_53 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_53.location = (0, 5000)
    prim_53.label = 'column3'
    val_54 = node_tree.nodes.new("ShaderNodeValue")
    val_54.location = (180, 5000)
    val_54.label = 'column3 radius'
    val_54.outputs[0].default_value = 5.175
    val_55 = node_tree.nodes.new("ShaderNodeValue")
    val_55.location = (360, 5000)
    val_55.label = 'column3 depth'
    val_55.outputs[0].default_value = 50
    node_tree.links.new(val_54.outputs["Value"], prim_53.inputs["Radius"])
    node_tree.links.new(val_55.outputs["Value"], prim_53.inputs["Depth"])
    prim_53.inputs["Vertices"].default_value = 32
    setpos_56 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_56.location = (0, 5200)
    setpos_56.label = 'column3 position'
    node_tree.links.new(prim_53.outputs["Mesh"], setpos_56.inputs["Geometry"])
    vec_57 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_57.location = (180, 5200)
    vec_57.label = 'column3 position offset'
    vec_57.vector = [30, -30, 0]
    node_tree.links.new(vec_57.outputs["Vector"], setpos_56.inputs["Offset"])
    prim_58 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_58.location = (0, 5400)
    prim_58.label = 'column4'
    val_59 = node_tree.nodes.new("ShaderNodeValue")
    val_59.location = (180, 5400)
    val_59.label = 'column4 radius'
    val_59.outputs[0].default_value = 5.175
    val_60 = node_tree.nodes.new("ShaderNodeValue")
    val_60.location = (360, 5400)
    val_60.label = 'column4 depth'
    val_60.outputs[0].default_value = 50
    node_tree.links.new(val_59.outputs["Value"], prim_58.inputs["Radius"])
    node_tree.links.new(val_60.outputs["Value"], prim_58.inputs["Depth"])
    prim_58.inputs["Vertices"].default_value = 32
    setpos_61 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_61.location = (0, 5600)
    setpos_61.label = 'column4 position'
    node_tree.links.new(prim_58.outputs["Mesh"], setpos_61.inputs["Geometry"])
    vec_62 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_62.location = (180, 5600)
    vec_62.label = 'column4 position offset'
    vec_62.vector = [-30, -30, 0]
    node_tree.links.new(vec_62.outputs["Vector"], setpos_61.inputs["Offset"])
    prim_63 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_63.location = (0, 5800)
    prim_63.label = 'h_light'
    vec_64 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_64.location = (180, 5800)
    vec_64.label = "h_light size"
    vec_64.vector = [80, 38, 30]
    node_tree.links.new(vec_64.outputs["Vector"], prim_63.inputs["Size"])
    setpos_65 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_65.location = (0, 6000)
    setpos_65.label = 'h_light position'
    node_tree.links.new(prim_63.outputs["Mesh"], setpos_65.inputs["Geometry"])
    vec_66 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_66.location = (180, 6000)
    vec_66.label = 'h_light position offset'
    vec_66.vector = [0, 0, 15]
    node_tree.links.new(vec_66.outputs["Vector"], setpos_65.inputs["Offset"])
    prim_67 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_67.location = (0, 6200)
    prim_67.label = 'h_film_35mm_3'
    val_68 = node_tree.nodes.new("ShaderNodeValue")
    val_68.location = (180, 6200)
    val_68.label = 'h_film_35mm_3 radius'
    val_68.outputs[0].default_value = 15
    val_69 = node_tree.nodes.new("ShaderNodeValue")
    val_69.location = (360, 6200)
    val_69.label = 'h_film_35mm_3 depth'
    val_69.outputs[0].default_value = 8
    node_tree.links.new(val_68.outputs["Value"], prim_67.inputs["Radius"])
    node_tree.links.new(val_69.outputs["Value"], prim_67.inputs["Depth"])
    prim_67.inputs["Vertices"].default_value = 32
    setpos_70 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_70.location = (0, 6400)
    setpos_70.label = 'h_film_35mm_3 position'
    node_tree.links.new(prim_67.outputs["Mesh"], setpos_70.inputs["Geometry"])
    vec_71 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_71.location = (180, 6400)
    vec_71.label = 'h_film_35mm_3 position offset'
    vec_71.vector = [0, 30, 9]
    node_tree.links.new(vec_71.outputs["Vector"], setpos_70.inputs["Offset"])
    prim_72 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_72.location = (0, 6600)
    prim_72.label = 'h_film_35mm_4'
    val_73 = node_tree.nodes.new("ShaderNodeValue")
    val_73.location = (180, 6600)
    val_73.label = 'h_film_35mm_4 radius'
    val_73.outputs[0].default_value = 15
    val_74 = node_tree.nodes.new("ShaderNodeValue")
    val_74.location = (360, 6600)
    val_74.label = 'h_film_35mm_4 depth'
    val_74.outputs[0].default_value = 8
    node_tree.links.new(val_73.outputs["Value"], prim_72.inputs["Radius"])
    node_tree.links.new(val_74.outputs["Value"], prim_72.inputs["Depth"])
    prim_72.inputs["Vertices"].default_value = 32
    setpos_75 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_75.location = (0, 6800)
    setpos_75.label = 'h_film_35mm_4 position'
    node_tree.links.new(prim_72.outputs["Mesh"], setpos_75.inputs["Geometry"])
    vec_76 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_76.location = (180, 6800)
    vec_76.label = 'h_film_35mm_4 position offset'
    vec_76.vector = [0, 38, 8]
    node_tree.links.new(vec_76.outputs["Vector"], setpos_75.inputs["Offset"])
    bool_77 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_77.location = (0, 7000)
    bool_77.label = 'difference'
    bool_77.operation = "DIFFERENCE"
    bool_77.solver = "EXACT"
    node_tree.links.new(bool_42.outputs["Mesh"], bool_77.inputs[0])
    node_tree.links.new(setpos_46.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_51.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_56.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_61.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_65.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_70.outputs["Geometry"], bool_77.inputs[1])
    node_tree.links.new(setpos_75.outputs["Geometry"], bool_77.inputs[1])
    xform_78 = node_tree.nodes.new("GeometryNodeTransform")
    xform_78.location = (0, 7200)
    xform_78.label = 'difference translate'
    node_tree.links.new(bool_77.outputs["Mesh"], xform_78.inputs["Geometry"])
    vec_79 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_79.location = (180, 7200)
    vec_79.label = 'difference translate translation'
    vec_79.vector = [0, 0, 1]
    node_tree.links.new(vec_79.outputs["Vector"], xform_78.inputs["Translation"])
    out_80 = node_tree.nodes.new("NodeGroupOutput")
    out_80.location = (0, 7400)
    out_80.label = "output"
    node_tree.links.new(xform_78.outputs[0], out_80.inputs[0])

    return node_tree


# Execute
setup()

