import bpy


def setup(object_name='film_support_base'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'film_support_base'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "film_support_base size"
    vec_2.vector = [44, 10, 10]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    prim_3 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_3.location = (0, 400)
    prim_3.label = 'h_film_support_base'
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = "h_film_support_base size"
    vec_4.vector = [41.25, 7.25, 10]
    node_tree.links.new(vec_4.outputs["Vector"], prim_3.inputs["Size"])
    setpos_5 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_5.location = (0, 600)
    setpos_5.label = 'h_film_support_base position'
    node_tree.links.new(prim_3.outputs["Mesh"], setpos_5.inputs["Geometry"])
    vec_6 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_6.location = (180, 600)
    vec_6.label = 'h_film_support_base position offset'
    vec_6.vector = [0, 0, 1]
    node_tree.links.new(vec_6.outputs["Vector"], setpos_5.inputs["Offset"])
    bool_7 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_7.location = (0, 800)
    bool_7.label = 'difference'
    bool_7.operation = "DIFFERENCE"
    bool_7.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_7.inputs[0])
    node_tree.links.new(setpos_5.outputs["Geometry"], bool_7.inputs[1])
    out_8 = node_tree.nodes.new("NodeGroupOutput")
    out_8.location = (0, 1000)
    out_8.label = "output"
    node_tree.links.new(bool_7.outputs[0], out_8.inputs[0])

    return node_tree


# Execute
setup()

