import bpy


def setup(object_name='h_motor_cog'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'connector'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'connector radius'
    val_2.outputs[0].default_value = 2.5
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'connector depth'
    val_3.outputs[0].default_value = 30
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_4.location = (0, 400)
    prim_4.label = 'connector'
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = "connector size"
    vec_5.vector = [6.125, 3.8, 30]
    node_tree.links.new(vec_5.outputs["Vector"], prim_4.inputs["Size"])
    bool_6 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_6.location = (0, 600)
    bool_6.label = 'intersect'
    bool_6.operation = "INTERSECT"
    bool_6.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_6.inputs[1])
    node_tree.links.new(prim_4.outputs["Mesh"], bool_6.inputs[1])
    out_7 = node_tree.nodes.new("NodeGroupOutput")
    out_7.location = (0, 800)
    out_7.label = "output"
    node_tree.links.new(bool_6.outputs[0], out_7.inputs[0])

    return node_tree


# Execute
setup()

