import bpy


def setup(object_name='lamp_support_2'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'lamp_support'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "lamp_support size"
    vec_2.vector = [90, 90, 3]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'lamp_support position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'lamp_support position offset'
    vec_4.vector = [0, 0, -8]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_5.location = (0, 600)
    prim_5.label = 'column1'
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (180, 600)
    val_6.label = 'column1 radius'
    val_6.outputs[0].default_value = 6.925
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (360, 600)
    val_7.label = 'column1 depth'
    val_7.outputs[0].default_value = 15
    node_tree.links.new(val_6.outputs["Value"], prim_5.inputs["Radius"])
    node_tree.links.new(val_7.outputs["Value"], prim_5.inputs["Depth"])
    prim_5.inputs["Vertices"].default_value = 32
    setpos_8 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_8.location = (0, 800)
    setpos_8.label = 'column1 position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_8.inputs["Geometry"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (180, 800)
    vec_9.label = 'column1 position offset'
    vec_9.vector = [30, 30, 0]
    node_tree.links.new(vec_9.outputs["Vector"], setpos_8.inputs["Offset"])
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_10.location = (0, 1000)
    prim_10.label = 'column2'
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (180, 1000)
    val_11.label = 'column2 radius'
    val_11.outputs[0].default_value = 6.925
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (360, 1000)
    val_12.label = 'column2 depth'
    val_12.outputs[0].default_value = 15
    node_tree.links.new(val_11.outputs["Value"], prim_10.inputs["Radius"])
    node_tree.links.new(val_12.outputs["Value"], prim_10.inputs["Depth"])
    prim_10.inputs["Vertices"].default_value = 32
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1200)
    setpos_13.label = 'column2 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = 'column2 position offset'
    vec_14.vector = [-30, 30, 0]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_15.location = (0, 1400)
    prim_15.label = 'column3'
    val_16 = node_tree.nodes.new("ShaderNodeValue")
    val_16.location = (180, 1400)
    val_16.label = 'column3 radius'
    val_16.outputs[0].default_value = 6.925
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (360, 1400)
    val_17.label = 'column3 depth'
    val_17.outputs[0].default_value = 15
    node_tree.links.new(val_16.outputs["Value"], prim_15.inputs["Radius"])
    node_tree.links.new(val_17.outputs["Value"], prim_15.inputs["Depth"])
    prim_15.inputs["Vertices"].default_value = 32
    setpos_18 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_18.location = (0, 1600)
    setpos_18.label = 'column3 position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_18.inputs["Geometry"])
    vec_19 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_19.location = (180, 1600)
    vec_19.label = 'column3 position offset'
    vec_19.vector = [30, -30, 0]
    node_tree.links.new(vec_19.outputs["Vector"], setpos_18.inputs["Offset"])
    prim_20 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_20.location = (0, 1800)
    prim_20.label = 'column4'
    val_21 = node_tree.nodes.new("ShaderNodeValue")
    val_21.location = (180, 1800)
    val_21.label = 'column4 radius'
    val_21.outputs[0].default_value = 6.925
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (360, 1800)
    val_22.label = 'column4 depth'
    val_22.outputs[0].default_value = 15
    node_tree.links.new(val_21.outputs["Value"], prim_20.inputs["Radius"])
    node_tree.links.new(val_22.outputs["Value"], prim_20.inputs["Depth"])
    prim_20.inputs["Vertices"].default_value = 32
    setpos_23 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_23.location = (0, 2000)
    setpos_23.label = 'column4 position'
    node_tree.links.new(prim_20.outputs["Mesh"], setpos_23.inputs["Geometry"])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (180, 2000)
    vec_24.label = 'column4 position offset'
    vec_24.vector = [-30, -30, 0]
    node_tree.links.new(vec_24.outputs["Vector"], setpos_23.inputs["Offset"])
    bool_25 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_25.location = (0, 2200)
    bool_25.label = 'union'
    bool_25.operation = "UNION"
    bool_25.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_8.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_18.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_23.outputs["Geometry"], bool_25.inputs[1])
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (0, 2400)
    prim_26.label = 'column1'
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (180, 2400)
    val_27.label = 'column1 radius'
    val_27.outputs[0].default_value = 5.05
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (360, 2400)
    val_28.label = 'column1 depth'
    val_28.outputs[0].default_value = 25
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (0, 2600)
    setpos_29.label = 'column1 position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_29.inputs["Geometry"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2600)
    vec_30.label = 'column1 position offset'
    vec_30.vector = [30, 30, 0]
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (0, 2800)
    prim_31.label = 'column2'
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (180, 2800)
    val_32.label = 'column2 radius'
    val_32.outputs[0].default_value = 5.05
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (360, 2800)
    val_33.label = 'column2 depth'
    val_33.outputs[0].default_value = 25
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 32
    setpos_34 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_34.location = (0, 3000)
    setpos_34.label = 'column2 position'
    node_tree.links.new(prim_31.outputs["Mesh"], setpos_34.inputs["Geometry"])
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (180, 3000)
    vec_35.label = 'column2 position offset'
    vec_35.vector = [-30, 30, 0]
    node_tree.links.new(vec_35.outputs["Vector"], setpos_34.inputs["Offset"])
    prim_36 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_36.location = (0, 3200)
    prim_36.label = 'column3'
    val_37 = node_tree.nodes.new("ShaderNodeValue")
    val_37.location = (180, 3200)
    val_37.label = 'column3 radius'
    val_37.outputs[0].default_value = 5.05
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (360, 3200)
    val_38.label = 'column3 depth'
    val_38.outputs[0].default_value = 25
    node_tree.links.new(val_37.outputs["Value"], prim_36.inputs["Radius"])
    node_tree.links.new(val_38.outputs["Value"], prim_36.inputs["Depth"])
    prim_36.inputs["Vertices"].default_value = 32
    setpos_39 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_39.location = (0, 3400)
    setpos_39.label = 'column3 position'
    node_tree.links.new(prim_36.outputs["Mesh"], setpos_39.inputs["Geometry"])
    vec_40 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_40.location = (180, 3400)
    vec_40.label = 'column3 position offset'
    vec_40.vector = [30, -30, 0]
    node_tree.links.new(vec_40.outputs["Vector"], setpos_39.inputs["Offset"])
    prim_41 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_41.location = (0, 3600)
    prim_41.label = 'column4'
    val_42 = node_tree.nodes.new("ShaderNodeValue")
    val_42.location = (180, 3600)
    val_42.label = 'column4 radius'
    val_42.outputs[0].default_value = 5.05
    val_43 = node_tree.nodes.new("ShaderNodeValue")
    val_43.location = (360, 3600)
    val_43.label = 'column4 depth'
    val_43.outputs[0].default_value = 25
    node_tree.links.new(val_42.outputs["Value"], prim_41.inputs["Radius"])
    node_tree.links.new(val_43.outputs["Value"], prim_41.inputs["Depth"])
    prim_41.inputs["Vertices"].default_value = 32
    setpos_44 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_44.location = (0, 3800)
    setpos_44.label = 'column4 position'
    node_tree.links.new(prim_41.outputs["Mesh"], setpos_44.inputs["Geometry"])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (180, 3800)
    vec_45.label = 'column4 position offset'
    vec_45.vector = [-30, -30, 0]
    node_tree.links.new(vec_45.outputs["Vector"], setpos_44.inputs["Offset"])
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_46.location = (0, 4000)
    prim_46.label = 'h_lamp'
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (180, 4000)
    val_47.label = 'h_lamp radius'
    val_47.outputs[0].default_value = 10.375
    val_48 = node_tree.nodes.new("ShaderNodeValue")
    val_48.location = (360, 4000)
    val_48.label = 'h_lamp depth'
    val_48.outputs[0].default_value = 3
    node_tree.links.new(val_47.outputs["Value"], prim_46.inputs["Radius"])
    node_tree.links.new(val_48.outputs["Value"], prim_46.inputs["Depth"])
    prim_46.inputs["Vertices"].default_value = 32
    setpos_49 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_49.location = (0, 4200)
    setpos_49.label = 'h_lamp position'
    node_tree.links.new(prim_46.outputs["Mesh"], setpos_49.inputs["Geometry"])
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (180, 4200)
    vec_50.label = 'h_lamp position offset'
    vec_50.vector = [0, -16, -7]
    node_tree.links.new(vec_50.outputs["Vector"], setpos_49.inputs["Offset"])
    prim_51 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_51.location = (0, 4400)
    prim_51.label = 'h_lamp'
    val_52 = node_tree.nodes.new("ShaderNodeValue")
    val_52.location = (180, 4400)
    val_52.label = 'h_lamp radius'
    val_52.outputs[0].default_value = 10.375
    val_53 = node_tree.nodes.new("ShaderNodeValue")
    val_53.location = (360, 4400)
    val_53.label = 'h_lamp depth'
    val_53.outputs[0].default_value = 3
    node_tree.links.new(val_52.outputs["Value"], prim_51.inputs["Radius"])
    node_tree.links.new(val_53.outputs["Value"], prim_51.inputs["Depth"])
    prim_51.inputs["Vertices"].default_value = 32
    setpos_54 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_54.location = (0, 4600)
    setpos_54.label = 'h_lamp position'
    node_tree.links.new(prim_51.outputs["Mesh"], setpos_54.inputs["Geometry"])
    vec_55 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_55.location = (180, 4600)
    vec_55.label = 'h_lamp position offset'
    vec_55.vector = [-12, 10, -7]
    node_tree.links.new(vec_55.outputs["Vector"], setpos_54.inputs["Offset"])
    prim_56 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_56.location = (0, 4800)
    prim_56.label = 'h_lamp'
    val_57 = node_tree.nodes.new("ShaderNodeValue")
    val_57.location = (180, 4800)
    val_57.label = 'h_lamp radius'
    val_57.outputs[0].default_value = 10.375
    val_58 = node_tree.nodes.new("ShaderNodeValue")
    val_58.location = (360, 4800)
    val_58.label = 'h_lamp depth'
    val_58.outputs[0].default_value = 3
    node_tree.links.new(val_57.outputs["Value"], prim_56.inputs["Radius"])
    node_tree.links.new(val_58.outputs["Value"], prim_56.inputs["Depth"])
    prim_56.inputs["Vertices"].default_value = 32
    setpos_59 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_59.location = (0, 5000)
    setpos_59.label = 'h_lamp position'
    node_tree.links.new(prim_56.outputs["Mesh"], setpos_59.inputs["Geometry"])
    vec_60 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_60.location = (180, 5000)
    vec_60.label = 'h_lamp position offset'
    vec_60.vector = [12, 10, -7]
    node_tree.links.new(vec_60.outputs["Vector"], setpos_59.inputs["Offset"])
    prim_61 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_61.location = (0, 5200)
    prim_61.label = 'h_lamp'
    val_62 = node_tree.nodes.new("ShaderNodeValue")
    val_62.location = (180, 5200)
    val_62.label = 'h_lamp radius'
    val_62.outputs[0].default_value = 4
    val_63 = node_tree.nodes.new("ShaderNodeValue")
    val_63.location = (360, 5200)
    val_63.label = 'h_lamp depth'
    val_63.outputs[0].default_value = 10
    node_tree.links.new(val_62.outputs["Value"], prim_61.inputs["Radius"])
    node_tree.links.new(val_63.outputs["Value"], prim_61.inputs["Depth"])
    prim_61.inputs["Vertices"].default_value = 32
    setpos_64 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_64.location = (0, 5400)
    setpos_64.label = 'h_lamp position'
    node_tree.links.new(prim_61.outputs["Mesh"], setpos_64.inputs["Geometry"])
    vec_65 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_65.location = (180, 5400)
    vec_65.label = 'h_lamp position offset'
    vec_65.vector = [0, 0, -7]
    node_tree.links.new(vec_65.outputs["Vector"], setpos_64.inputs["Offset"])
    bool_66 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_66.location = (0, 5600)
    bool_66.label = 'difference'
    bool_66.operation = "DIFFERENCE"
    bool_66.solver = "EXACT"
    node_tree.links.new(bool_25.outputs["Mesh"], bool_66.inputs[0])
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_34.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_39.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_44.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_49.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_54.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_59.outputs["Geometry"], bool_66.inputs[1])
    node_tree.links.new(setpos_64.outputs["Geometry"], bool_66.inputs[1])
    xform_67 = node_tree.nodes.new("GeometryNodeTransform")
    xform_67.location = (0, 5800)
    xform_67.label = 'difference rotate'
    node_tree.links.new(bool_66.outputs["Mesh"], xform_67.inputs["Geometry"])
    vec_68 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_68.location = (180, 5800)
    vec_68.label = 'difference rotate rotation'
    vec_68.vector = [3.141592653589793, 0.0, 0.0]
    node_tree.links.new(vec_68.outputs["Vector"], xform_67.inputs["Rotation"])
    xform_69 = node_tree.nodes.new("GeometryNodeTransform")
    xform_69.location = (0, 6000)
    xform_69.label = 'difference rotate translate'
    node_tree.links.new(xform_67.outputs["Geometry"], xform_69.inputs["Geometry"])
    vec_70 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_70.location = (180, 6000)
    vec_70.label = 'difference rotate translate translation'
    vec_70.vector = [0, 0, -40]
    node_tree.links.new(vec_70.outputs["Vector"], xform_69.inputs["Translation"])
    out_71 = node_tree.nodes.new("NodeGroupOutput")
    out_71.location = (0, 6200)
    out_71.label = "output"
    node_tree.links.new(xform_69.outputs[0], out_71.inputs[0])

    return node_tree


# Execute
setup()

