import bpy


def setup(object_name='lamp_support_1'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'column1'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'column1 radius'
    val_2.outputs[0].default_value = 6.925
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'column1 depth'
    val_3.outputs[0].default_value = 20
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    setpos_4 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_4.location = (0, 400)
    setpos_4.label = 'column1 position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_4.inputs["Geometry"])
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = 'column1 position offset'
    vec_5.vector = [30, 30, 0]
    node_tree.links.new(vec_5.outputs["Vector"], setpos_4.inputs["Offset"])
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (0, 600)
    prim_6.label = 'column2'
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (180, 600)
    val_7.label = 'column2 radius'
    val_7.outputs[0].default_value = 6.925
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (360, 600)
    val_8.label = 'column2 depth'
    val_8.outputs[0].default_value = 20
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 32
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 800)
    setpos_9.label = 'column2 position'
    node_tree.links.new(prim_6.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 800)
    vec_10.label = 'column2 position offset'
    vec_10.vector = [-30, 30, 0]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_11.location = (0, 1000)
    prim_11.label = 'column3'
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (180, 1000)
    val_12.label = 'column3 radius'
    val_12.outputs[0].default_value = 6.925
    val_13 = node_tree.nodes.new("ShaderNodeValue")
    val_13.location = (360, 1000)
    val_13.label = 'column3 depth'
    val_13.outputs[0].default_value = 20
    node_tree.links.new(val_12.outputs["Value"], prim_11.inputs["Radius"])
    node_tree.links.new(val_13.outputs["Value"], prim_11.inputs["Depth"])
    prim_11.inputs["Vertices"].default_value = 32
    setpos_14 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_14.location = (0, 1200)
    setpos_14.label = 'column3 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_14.inputs["Geometry"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (180, 1200)
    vec_15.label = 'column3 position offset'
    vec_15.vector = [30, -30, 0]
    node_tree.links.new(vec_15.outputs["Vector"], setpos_14.inputs["Offset"])
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (0, 1400)
    prim_16.label = 'column4'
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (180, 1400)
    val_17.label = 'column4 radius'
    val_17.outputs[0].default_value = 6.925
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (360, 1400)
    val_18.label = 'column4 depth'
    val_18.outputs[0].default_value = 20
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    setpos_19 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_19.location = (0, 1600)
    setpos_19.label = 'column4 position'
    node_tree.links.new(prim_16.outputs["Mesh"], setpos_19.inputs["Geometry"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (180, 1600)
    vec_20.label = 'column4 position offset'
    vec_20.vector = [-30, -30, 0]
    node_tree.links.new(vec_20.outputs["Vector"], setpos_19.inputs["Offset"])
    prim_21 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_21.location = (0, 1800)
    prim_21.label = 'lamp_support'
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (180, 1800)
    vec_22.label = "lamp_support size"
    vec_22.vector = [90, 90, 4]
    node_tree.links.new(vec_22.outputs["Vector"], prim_21.inputs["Size"])
    setpos_23 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_23.location = (0, 2000)
    setpos_23.label = 'lamp_support position'
    node_tree.links.new(prim_21.outputs["Mesh"], setpos_23.inputs["Geometry"])
    vec_24 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_24.location = (180, 2000)
    vec_24.label = 'lamp_support position offset'
    vec_24.vector = [0, 0, 10]
    node_tree.links.new(vec_24.outputs["Vector"], setpos_23.inputs["Offset"])
    bool_25 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_25.location = (0, 2200)
    bool_25.label = 'union'
    bool_25.operation = "UNION"
    bool_25.solver = "EXACT"
    node_tree.links.new(setpos_4.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_14.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_19.outputs["Geometry"], bool_25.inputs[1])
    node_tree.links.new(setpos_23.outputs["Geometry"], bool_25.inputs[1])
    prim_26 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_26.location = (0, 2400)
    prim_26.label = 'column1'
    val_27 = node_tree.nodes.new("ShaderNodeValue")
    val_27.location = (180, 2400)
    val_27.label = 'column1 radius'
    val_27.outputs[0].default_value = 5.05
    val_28 = node_tree.nodes.new("ShaderNodeValue")
    val_28.location = (360, 2400)
    val_28.label = 'column1 depth'
    val_28.outputs[0].default_value = 20
    node_tree.links.new(val_27.outputs["Value"], prim_26.inputs["Radius"])
    node_tree.links.new(val_28.outputs["Value"], prim_26.inputs["Depth"])
    prim_26.inputs["Vertices"].default_value = 32
    setpos_29 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_29.location = (0, 2600)
    setpos_29.label = 'column1 position'
    node_tree.links.new(prim_26.outputs["Mesh"], setpos_29.inputs["Geometry"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2600)
    vec_30.label = 'column1 position offset'
    vec_30.vector = [30, 30, 0]
    node_tree.links.new(vec_30.outputs["Vector"], setpos_29.inputs["Offset"])
    prim_31 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_31.location = (0, 2800)
    prim_31.label = 'column2'
    val_32 = node_tree.nodes.new("ShaderNodeValue")
    val_32.location = (180, 2800)
    val_32.label = 'column2 radius'
    val_32.outputs[0].default_value = 5.05
    val_33 = node_tree.nodes.new("ShaderNodeValue")
    val_33.location = (360, 2800)
    val_33.label = 'column2 depth'
    val_33.outputs[0].default_value = 20
    node_tree.links.new(val_32.outputs["Value"], prim_31.inputs["Radius"])
    node_tree.links.new(val_33.outputs["Value"], prim_31.inputs["Depth"])
    prim_31.inputs["Vertices"].default_value = 32
    setpos_34 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_34.location = (0, 3000)
    setpos_34.label = 'column2 position'
    node_tree.links.new(prim_31.outputs["Mesh"], setpos_34.inputs["Geometry"])
    vec_35 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_35.location = (180, 3000)
    vec_35.label = 'column2 position offset'
    vec_35.vector = [-30, 30, 0]
    node_tree.links.new(vec_35.outputs["Vector"], setpos_34.inputs["Offset"])
    prim_36 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_36.location = (0, 3200)
    prim_36.label = 'column3'
    val_37 = node_tree.nodes.new("ShaderNodeValue")
    val_37.location = (180, 3200)
    val_37.label = 'column3 radius'
    val_37.outputs[0].default_value = 5.05
    val_38 = node_tree.nodes.new("ShaderNodeValue")
    val_38.location = (360, 3200)
    val_38.label = 'column3 depth'
    val_38.outputs[0].default_value = 20
    node_tree.links.new(val_37.outputs["Value"], prim_36.inputs["Radius"])
    node_tree.links.new(val_38.outputs["Value"], prim_36.inputs["Depth"])
    prim_36.inputs["Vertices"].default_value = 32
    setpos_39 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_39.location = (0, 3400)
    setpos_39.label = 'column3 position'
    node_tree.links.new(prim_36.outputs["Mesh"], setpos_39.inputs["Geometry"])
    vec_40 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_40.location = (180, 3400)
    vec_40.label = 'column3 position offset'
    vec_40.vector = [30, -30, 0]
    node_tree.links.new(vec_40.outputs["Vector"], setpos_39.inputs["Offset"])
    prim_41 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_41.location = (0, 3600)
    prim_41.label = 'column4'
    val_42 = node_tree.nodes.new("ShaderNodeValue")
    val_42.location = (180, 3600)
    val_42.label = 'column4 radius'
    val_42.outputs[0].default_value = 5.05
    val_43 = node_tree.nodes.new("ShaderNodeValue")
    val_43.location = (360, 3600)
    val_43.label = 'column4 depth'
    val_43.outputs[0].default_value = 20
    node_tree.links.new(val_42.outputs["Value"], prim_41.inputs["Radius"])
    node_tree.links.new(val_43.outputs["Value"], prim_41.inputs["Depth"])
    prim_41.inputs["Vertices"].default_value = 32
    setpos_44 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_44.location = (0, 3800)
    setpos_44.label = 'column4 position'
    node_tree.links.new(prim_41.outputs["Mesh"], setpos_44.inputs["Geometry"])
    vec_45 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_45.location = (180, 3800)
    vec_45.label = 'column4 position offset'
    vec_45.vector = [-30, -30, 0]
    node_tree.links.new(vec_45.outputs["Vector"], setpos_44.inputs["Offset"])
    prim_46 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_46.location = (0, 4000)
    prim_46.label = 'h_lamp'
    val_47 = node_tree.nodes.new("ShaderNodeValue")
    val_47.location = (180, 4000)
    val_47.label = 'h_lamp radius'
    val_47.outputs[0].default_value = 36
    val_48 = node_tree.nodes.new("ShaderNodeValue")
    val_48.location = (360, 4000)
    val_48.label = 'h_lamp depth'
    val_48.outputs[0].default_value = 20
    node_tree.links.new(val_47.outputs["Value"], prim_46.inputs["Radius"])
    node_tree.links.new(val_48.outputs["Value"], prim_46.inputs["Depth"])
    prim_46.inputs["Vertices"].default_value = 32
    setpos_49 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_49.location = (0, 4200)
    setpos_49.label = 'h_lamp position'
    node_tree.links.new(prim_46.outputs["Mesh"], setpos_49.inputs["Geometry"])
    vec_50 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_50.location = (180, 4200)
    vec_50.label = 'h_lamp position offset'
    vec_50.vector = [0, 0, 15]
    node_tree.links.new(vec_50.outputs["Vector"], setpos_49.inputs["Offset"])
    prim_51 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_51.location = (0, 4400)
    prim_51.label = 'column1'
    val_52 = node_tree.nodes.new("ShaderNodeValue")
    val_52.location = (180, 4400)
    val_52.label = 'column1 radius'
    val_52.outputs[0].default_value = 3.125
    val_53 = node_tree.nodes.new("ShaderNodeValue")
    val_53.location = (360, 4400)
    val_53.label = 'column1 depth'
    val_53.outputs[0].default_value = 30
    node_tree.links.new(val_52.outputs["Value"], prim_51.inputs["Radius"])
    node_tree.links.new(val_53.outputs["Value"], prim_51.inputs["Depth"])
    prim_51.inputs["Vertices"].default_value = 8
    setpos_54 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_54.location = (0, 4600)
    setpos_54.label = 'column1 position'
    node_tree.links.new(prim_51.outputs["Mesh"], setpos_54.inputs["Geometry"])
    vec_55 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_55.location = (180, 4600)
    vec_55.label = 'column1 position offset'
    vec_55.vector = [40, 40, 24]
    node_tree.links.new(vec_55.outputs["Vector"], setpos_54.inputs["Offset"])
    prim_56 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_56.location = (0, 4800)
    prim_56.label = 'column2'
    val_57 = node_tree.nodes.new("ShaderNodeValue")
    val_57.location = (180, 4800)
    val_57.label = 'column2 radius'
    val_57.outputs[0].default_value = 3.125
    val_58 = node_tree.nodes.new("ShaderNodeValue")
    val_58.location = (360, 4800)
    val_58.label = 'column2 depth'
    val_58.outputs[0].default_value = 30
    node_tree.links.new(val_57.outputs["Value"], prim_56.inputs["Radius"])
    node_tree.links.new(val_58.outputs["Value"], prim_56.inputs["Depth"])
    prim_56.inputs["Vertices"].default_value = 8
    setpos_59 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_59.location = (0, 5000)
    setpos_59.label = 'column2 position'
    node_tree.links.new(prim_56.outputs["Mesh"], setpos_59.inputs["Geometry"])
    vec_60 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_60.location = (180, 5000)
    vec_60.label = 'column2 position offset'
    vec_60.vector = [-40, 40, 24]
    node_tree.links.new(vec_60.outputs["Vector"], setpos_59.inputs["Offset"])
    prim_61 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_61.location = (0, 5200)
    prim_61.label = 'column3'
    val_62 = node_tree.nodes.new("ShaderNodeValue")
    val_62.location = (180, 5200)
    val_62.label = 'column3 radius'
    val_62.outputs[0].default_value = 3.125
    val_63 = node_tree.nodes.new("ShaderNodeValue")
    val_63.location = (360, 5200)
    val_63.label = 'column3 depth'
    val_63.outputs[0].default_value = 30
    node_tree.links.new(val_62.outputs["Value"], prim_61.inputs["Radius"])
    node_tree.links.new(val_63.outputs["Value"], prim_61.inputs["Depth"])
    prim_61.inputs["Vertices"].default_value = 8
    setpos_64 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_64.location = (0, 5400)
    setpos_64.label = 'column3 position'
    node_tree.links.new(prim_61.outputs["Mesh"], setpos_64.inputs["Geometry"])
    vec_65 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_65.location = (180, 5400)
    vec_65.label = 'column3 position offset'
    vec_65.vector = [40, -40, 24]
    node_tree.links.new(vec_65.outputs["Vector"], setpos_64.inputs["Offset"])
    prim_66 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_66.location = (0, 5600)
    prim_66.label = 'column4'
    val_67 = node_tree.nodes.new("ShaderNodeValue")
    val_67.location = (180, 5600)
    val_67.label = 'column4 radius'
    val_67.outputs[0].default_value = 3.125
    val_68 = node_tree.nodes.new("ShaderNodeValue")
    val_68.location = (360, 5600)
    val_68.label = 'column4 depth'
    val_68.outputs[0].default_value = 30
    node_tree.links.new(val_67.outputs["Value"], prim_66.inputs["Radius"])
    node_tree.links.new(val_68.outputs["Value"], prim_66.inputs["Depth"])
    prim_66.inputs["Vertices"].default_value = 8
    setpos_69 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_69.location = (0, 5800)
    setpos_69.label = 'column4 position'
    node_tree.links.new(prim_66.outputs["Mesh"], setpos_69.inputs["Geometry"])
    vec_70 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_70.location = (180, 5800)
    vec_70.label = 'column4 position offset'
    vec_70.vector = [-40, -40, 24]
    node_tree.links.new(vec_70.outputs["Vector"], setpos_69.inputs["Offset"])
    bool_71 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_71.location = (0, 6000)
    bool_71.label = 'difference'
    bool_71.operation = "DIFFERENCE"
    bool_71.solver = "EXACT"
    node_tree.links.new(bool_25.outputs["Mesh"], bool_71.inputs[0])
    node_tree.links.new(setpos_29.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_34.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_39.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_44.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_49.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_54.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_59.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_64.outputs["Geometry"], bool_71.inputs[1])
    node_tree.links.new(setpos_69.outputs["Geometry"], bool_71.inputs[1])
    xform_72 = node_tree.nodes.new("GeometryNodeTransform")
    xform_72.location = (0, 6200)
    xform_72.label = 'difference rotate'
    node_tree.links.new(bool_71.outputs["Mesh"], xform_72.inputs["Geometry"])
    vec_73 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_73.location = (180, 6200)
    vec_73.label = 'difference rotate rotation'
    vec_73.vector = [3.141592653589793, 0.0, 0.0]
    node_tree.links.new(vec_73.outputs["Vector"], xform_72.inputs["Rotation"])
    xform_74 = node_tree.nodes.new("GeometryNodeTransform")
    xform_74.location = (0, 6400)
    xform_74.label = 'difference rotate translate'
    node_tree.links.new(xform_72.outputs["Geometry"], xform_74.inputs["Geometry"])
    vec_75 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_75.location = (180, 6400)
    vec_75.label = 'difference rotate translate translation'
    vec_75.vector = [0, 0, -40]
    node_tree.links.new(vec_75.outputs["Vector"], xform_74.inputs["Translation"])
    out_76 = node_tree.nodes.new("NodeGroupOutput")
    out_76.location = (0, 6600)
    out_76.label = "output"
    node_tree.links.new(xform_74.outputs[0], out_76.inputs[0])

    return node_tree


# Execute
setup()

