import bpy


def setup(object_name='motor_support'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'motor_support'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "motor_support size"
    vec_2.vector = [100, 10, 12]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'motor_support position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'motor_support position offset'
    vec_4.vector = [0, 25, 0]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    prim_5 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_5.location = (0, 600)
    prim_5.label = 'column3'
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (180, 600)
    val_6.label = 'column3 radius'
    val_6.outputs[0].default_value = 6.925
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (360, 600)
    val_7.label = 'column3 depth'
    val_7.outputs[0].default_value = 12
    node_tree.links.new(val_6.outputs["Value"], prim_5.inputs["Radius"])
    node_tree.links.new(val_7.outputs["Value"], prim_5.inputs["Depth"])
    prim_5.inputs["Vertices"].default_value = 32
    setpos_8 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_8.location = (0, 800)
    setpos_8.label = 'column3 position'
    node_tree.links.new(prim_5.outputs["Mesh"], setpos_8.inputs["Geometry"])
    vec_9 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_9.location = (180, 800)
    vec_9.label = 'column3 position offset'
    vec_9.vector = [30, 30, 0]
    node_tree.links.new(vec_9.outputs["Vector"], setpos_8.inputs["Offset"])
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_10.location = (0, 1000)
    prim_10.label = 'column4'
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (180, 1000)
    val_11.label = 'column4 radius'
    val_11.outputs[0].default_value = 6.925
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (360, 1000)
    val_12.label = 'column4 depth'
    val_12.outputs[0].default_value = 12
    node_tree.links.new(val_11.outputs["Value"], prim_10.inputs["Radius"])
    node_tree.links.new(val_12.outputs["Value"], prim_10.inputs["Depth"])
    prim_10.inputs["Vertices"].default_value = 32
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1200)
    setpos_13.label = 'column4 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = 'column4 position offset'
    vec_14.vector = [-30, 30, 0]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    prim_15 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_15.location = (0, 1400)
    prim_15.label = 'screw_base_1'
    vec_16 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_16.location = (180, 1400)
    vec_16.label = "screw_base_1 size"
    vec_16.vector = [8, 20, 6]
    node_tree.links.new(vec_16.outputs["Vector"], prim_15.inputs["Size"])
    setpos_17 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_17.location = (0, 1600)
    setpos_17.label = 'screw_base_1 position'
    node_tree.links.new(prim_15.outputs["Mesh"], setpos_17.inputs["Geometry"])
    vec_18 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_18.location = (180, 1600)
    vec_18.label = 'screw_base_1 position offset'
    vec_18.vector = [17.5, 30, -3]
    node_tree.links.new(vec_18.outputs["Vector"], setpos_17.inputs["Offset"])
    prim_19 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_19.location = (0, 1800)
    prim_19.label = 'screw_base_2'
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (180, 1800)
    vec_20.label = "screw_base_2 size"
    vec_20.vector = [8, 20, 6]
    node_tree.links.new(vec_20.outputs["Vector"], prim_19.inputs["Size"])
    setpos_21 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_21.location = (0, 2000)
    setpos_21.label = 'screw_base_2 position'
    node_tree.links.new(prim_19.outputs["Mesh"], setpos_21.inputs["Geometry"])
    vec_22 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_22.location = (180, 2000)
    vec_22.label = 'screw_base_2 position offset'
    vec_22.vector = [-17.5, 30, -3]
    node_tree.links.new(vec_22.outputs["Vector"], setpos_21.inputs["Offset"])
    prim_23 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_23.location = (0, 2200)
    prim_23.label = 'screw_col_1'
    val_24 = node_tree.nodes.new("ShaderNodeValue")
    val_24.location = (180, 2200)
    val_24.label = 'screw_col_1 radius'
    val_24.outputs[0].default_value = 4
    val_25 = node_tree.nodes.new("ShaderNodeValue")
    val_25.location = (360, 2200)
    val_25.label = 'screw_col_1 depth'
    val_25.outputs[0].default_value = 7.5
    node_tree.links.new(val_24.outputs["Value"], prim_23.inputs["Radius"])
    node_tree.links.new(val_25.outputs["Value"], prim_23.inputs["Depth"])
    prim_23.inputs["Vertices"].default_value = 32
    setpos_26 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_26.location = (0, 2400)
    setpos_26.label = 'screw_col_1 position'
    node_tree.links.new(prim_23.outputs["Mesh"], setpos_26.inputs["Geometry"])
    vec_27 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_27.location = (180, 2400)
    vec_27.label = 'screw_col_1 position offset'
    vec_27.vector = [17.5, 40, -2.25]
    node_tree.links.new(vec_27.outputs["Vector"], setpos_26.inputs["Offset"])
    prim_28 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_28.location = (0, 2600)
    prim_28.label = 'screw_col_2'
    val_29 = node_tree.nodes.new("ShaderNodeValue")
    val_29.location = (180, 2600)
    val_29.label = 'screw_col_2 radius'
    val_29.outputs[0].default_value = 4
    val_30 = node_tree.nodes.new("ShaderNodeValue")
    val_30.location = (360, 2600)
    val_30.label = 'screw_col_2 depth'
    val_30.outputs[0].default_value = 7.5
    node_tree.links.new(val_29.outputs["Value"], prim_28.inputs["Radius"])
    node_tree.links.new(val_30.outputs["Value"], prim_28.inputs["Depth"])
    prim_28.inputs["Vertices"].default_value = 32
    setpos_31 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_31.location = (0, 2800)
    setpos_31.label = 'screw_col_2 position'
    node_tree.links.new(prim_28.outputs["Mesh"], setpos_31.inputs["Geometry"])
    vec_32 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_32.location = (180, 2800)
    vec_32.label = 'screw_col_2 position offset'
    vec_32.vector = [-17.5, 40, -2.25]
    node_tree.links.new(vec_32.outputs["Vector"], setpos_31.inputs["Offset"])
    bool_33 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_33.location = (0, 3000)
    bool_33.label = 'union'
    bool_33.operation = "UNION"
    bool_33.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_8.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_17.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_21.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_26.outputs["Geometry"], bool_33.inputs[1])
    node_tree.links.new(setpos_31.outputs["Geometry"], bool_33.inputs[1])
    prim_34 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_34.location = (0, 3200)
    prim_34.label = 'column3'
    val_35 = node_tree.nodes.new("ShaderNodeValue")
    val_35.location = (180, 3200)
    val_35.label = 'column3 radius'
    val_35.outputs[0].default_value = 5.175
    val_36 = node_tree.nodes.new("ShaderNodeValue")
    val_36.location = (360, 3200)
    val_36.label = 'column3 depth'
    val_36.outputs[0].default_value = 50
    node_tree.links.new(val_35.outputs["Value"], prim_34.inputs["Radius"])
    node_tree.links.new(val_36.outputs["Value"], prim_34.inputs["Depth"])
    prim_34.inputs["Vertices"].default_value = 32
    setpos_37 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_37.location = (0, 3400)
    setpos_37.label = 'column3 position'
    node_tree.links.new(prim_34.outputs["Mesh"], setpos_37.inputs["Geometry"])
    vec_38 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_38.location = (180, 3400)
    vec_38.label = 'column3 position offset'
    vec_38.vector = [30, 30, 0]
    node_tree.links.new(vec_38.outputs["Vector"], setpos_37.inputs["Offset"])
    prim_39 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_39.location = (0, 3600)
    prim_39.label = 'column4'
    val_40 = node_tree.nodes.new("ShaderNodeValue")
    val_40.location = (180, 3600)
    val_40.label = 'column4 radius'
    val_40.outputs[0].default_value = 5.175
    val_41 = node_tree.nodes.new("ShaderNodeValue")
    val_41.location = (360, 3600)
    val_41.label = 'column4 depth'
    val_41.outputs[0].default_value = 50
    node_tree.links.new(val_40.outputs["Value"], prim_39.inputs["Radius"])
    node_tree.links.new(val_41.outputs["Value"], prim_39.inputs["Depth"])
    prim_39.inputs["Vertices"].default_value = 32
    setpos_42 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_42.location = (0, 3800)
    setpos_42.label = 'column4 position'
    node_tree.links.new(prim_39.outputs["Mesh"], setpos_42.inputs["Geometry"])
    vec_43 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_43.location = (180, 3800)
    vec_43.label = 'column4 position offset'
    vec_43.vector = [-30, 30, 0]
    node_tree.links.new(vec_43.outputs["Vector"], setpos_42.inputs["Offset"])
    prim_44 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_44.location = (0, 4000)
    prim_44.label = 'h_motor'
    val_45 = node_tree.nodes.new("ShaderNodeValue")
    val_45.location = (180, 4000)
    val_45.label = 'h_motor radius'
    val_45.outputs[0].default_value = 15
    val_46 = node_tree.nodes.new("ShaderNodeValue")
    val_46.location = (360, 4000)
    val_46.label = 'h_motor depth'
    val_46.outputs[0].default_value = 12
    node_tree.links.new(val_45.outputs["Value"], prim_44.inputs["Radius"])
    node_tree.links.new(val_46.outputs["Value"], prim_44.inputs["Depth"])
    prim_44.inputs["Vertices"].default_value = 32
    setpos_47 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_47.location = (0, 4200)
    setpos_47.label = 'h_motor position'
    node_tree.links.new(prim_44.outputs["Mesh"], setpos_47.inputs["Geometry"])
    vec_48 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_48.location = (180, 4200)
    vec_48.label = 'h_motor position offset'
    vec_48.vector = [0, 38, 0]
    node_tree.links.new(vec_48.outputs["Vector"], setpos_47.inputs["Offset"])
    prim_49 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_49.location = (0, 4400)
    prim_49.label = 'h_screw_col_1'
    val_50 = node_tree.nodes.new("ShaderNodeValue")
    val_50.location = (180, 4400)
    val_50.label = 'h_screw_col_1 radius'
    val_50.outputs[0].default_value = 2.125
    val_51 = node_tree.nodes.new("ShaderNodeValue")
    val_51.location = (360, 4400)
    val_51.label = 'h_screw_col_1 depth'
    val_51.outputs[0].default_value = 6
    node_tree.links.new(val_50.outputs["Value"], prim_49.inputs["Radius"])
    node_tree.links.new(val_51.outputs["Value"], prim_49.inputs["Depth"])
    prim_49.inputs["Vertices"].default_value = 32
    setpos_52 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_52.location = (0, 4600)
    setpos_52.label = 'h_screw_col_1 position'
    node_tree.links.new(prim_49.outputs["Mesh"], setpos_52.inputs["Geometry"])
    vec_53 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_53.location = (180, 4600)
    vec_53.label = 'h_screw_col_1 position offset'
    vec_53.vector = [17.5, 40, -1.5]
    node_tree.links.new(vec_53.outputs["Vector"], setpos_52.inputs["Offset"])
    prim_54 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_54.location = (0, 4800)
    prim_54.label = 'h_screw_col_2'
    val_55 = node_tree.nodes.new("ShaderNodeValue")
    val_55.location = (180, 4800)
    val_55.label = 'h_screw_col_2 radius'
    val_55.outputs[0].default_value = 2.125
    val_56 = node_tree.nodes.new("ShaderNodeValue")
    val_56.location = (360, 4800)
    val_56.label = 'h_screw_col_2 depth'
    val_56.outputs[0].default_value = 6
    node_tree.links.new(val_55.outputs["Value"], prim_54.inputs["Radius"])
    node_tree.links.new(val_56.outputs["Value"], prim_54.inputs["Depth"])
    prim_54.inputs["Vertices"].default_value = 32
    setpos_57 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_57.location = (0, 5000)
    setpos_57.label = 'h_screw_col_2 position'
    node_tree.links.new(prim_54.outputs["Mesh"], setpos_57.inputs["Geometry"])
    vec_58 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_58.location = (180, 5000)
    vec_58.label = 'h_screw_col_2 position offset'
    vec_58.vector = [-17.5, 40, -1.5]
    node_tree.links.new(vec_58.outputs["Vector"], setpos_57.inputs["Offset"])
    bool_59 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_59.location = (0, 5200)
    bool_59.label = 'difference'
    bool_59.operation = "DIFFERENCE"
    bool_59.solver = "EXACT"
    node_tree.links.new(bool_33.outputs["Mesh"], bool_59.inputs[0])
    node_tree.links.new(setpos_37.outputs["Geometry"], bool_59.inputs[1])
    node_tree.links.new(setpos_42.outputs["Geometry"], bool_59.inputs[1])
    node_tree.links.new(setpos_47.outputs["Geometry"], bool_59.inputs[1])
    node_tree.links.new(setpos_52.outputs["Geometry"], bool_59.inputs[1])
    node_tree.links.new(setpos_57.outputs["Geometry"], bool_59.inputs[1])
    xform_60 = node_tree.nodes.new("GeometryNodeTransform")
    xform_60.location = (0, 5400)
    xform_60.label = 'difference rotate'
    node_tree.links.new(bool_59.outputs["Mesh"], xform_60.inputs["Geometry"])
    vec_61 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_61.location = (180, 5400)
    vec_61.label = 'difference rotate rotation'
    vec_61.vector = [0.0, 3.141592653589793, 0.0]
    node_tree.links.new(vec_61.outputs["Vector"], xform_60.inputs["Rotation"])
    out_62 = node_tree.nodes.new("NodeGroupOutput")
    out_62.location = (0, 5600)
    out_62.label = "output"
    node_tree.links.new(xform_60.outputs[0], out_62.inputs[0])

    return node_tree


# Execute
setup()

