import bpy


def setup(object_name='sensor_support_j1_column'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'column1'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'column1 radius'
    val_2.outputs[0].default_value = 4.9875
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'column1 depth'
    val_3.outputs[0].default_value = 10
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    setpos_4 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_4.location = (0, 400)
    setpos_4.label = 'column1 position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_4.inputs["Geometry"])
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = 'column1 position offset'
    vec_5.vector = [0, 0, 7.5]
    node_tree.links.new(vec_5.outputs["Vector"], setpos_4.inputs["Offset"])
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (0, 600)
    prim_6.label = 'column2'
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (180, 600)
    val_7.label = 'column2 radius'
    val_7.outputs[0].default_value = 8.925
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (360, 600)
    val_8.label = 'column2 depth'
    val_8.outputs[0].default_value = 15
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 32
    bool_9 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_9.location = (0, 800)
    bool_9.label = 'union'
    bool_9.operation = "UNION"
    bool_9.solver = "EXACT"
    node_tree.links.new(setpos_4.outputs["Geometry"], bool_9.inputs[1])
    node_tree.links.new(prim_6.outputs["Mesh"], bool_9.inputs[1])
    prim_10 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_10.location = (0, 1000)
    prim_10.label = 'column3'
    val_11 = node_tree.nodes.new("ShaderNodeValue")
    val_11.location = (180, 1000)
    val_11.label = 'column3 radius'
    val_11.outputs[0].default_value = 4.925
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (360, 1000)
    val_12.label = 'column3 depth'
    val_12.outputs[0].default_value = 15
    node_tree.links.new(val_11.outputs["Value"], prim_10.inputs["Radius"])
    node_tree.links.new(val_12.outputs["Value"], prim_10.inputs["Depth"])
    prim_10.inputs["Vertices"].default_value = 32
    setpos_13 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_13.location = (0, 1200)
    setpos_13.label = 'column3 position'
    node_tree.links.new(prim_10.outputs["Mesh"], setpos_13.inputs["Geometry"])
    vec_14 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_14.location = (180, 1200)
    vec_14.label = 'column3 position offset'
    vec_14.vector = [0, 0, -5]
    node_tree.links.new(vec_14.outputs["Vector"], setpos_13.inputs["Offset"])
    bool_15 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_15.location = (0, 1400)
    bool_15.label = 'difference'
    bool_15.operation = "DIFFERENCE"
    bool_15.solver = "EXACT"
    node_tree.links.new(bool_9.outputs["Mesh"], bool_15.inputs[0])
    node_tree.links.new(setpos_13.outputs["Geometry"], bool_15.inputs[1])
    out_16 = node_tree.nodes.new("NodeGroupOutput")
    out_16.location = (0, 1600)
    out_16.label = "output"
    node_tree.links.new(bool_15.outputs[0], out_16.inputs[0])

    return node_tree


# Execute
setup()

