import bpy


def setup(object_name='sensor_support_j1'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_1.location = (0, 200)
    prim_1.label = 'sensor_support'
    vec_2 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_2.location = (180, 200)
    vec_2.label = "sensor_support size"
    vec_2.vector = [80, 80, 4]
    node_tree.links.new(vec_2.outputs["Vector"], prim_1.inputs["Size"])
    setpos_3 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_3.location = (0, 400)
    setpos_3.label = 'sensor_support position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_3.inputs["Geometry"])
    vec_4 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_4.location = (180, 400)
    vec_4.label = 'sensor_support position offset'
    vec_4.vector = [0, 0, -15]
    node_tree.links.new(vec_4.outputs["Vector"], setpos_3.inputs["Offset"])
    bool_5 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_5.location = (0, 600)
    bool_5.label = 'union'
    bool_5.operation = "UNION"
    bool_5.solver = "EXACT"
    node_tree.links.new(setpos_3.outputs["Geometry"], bool_5.inputs[1])
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (0, 800)
    prim_6.label = 'column1'
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (180, 800)
    val_7.label = 'column1 radius'
    val_7.outputs[0].default_value = 5.05
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (360, 800)
    val_8.label = 'column1 depth'
    val_8.outputs[0].default_value = 100
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 32
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 1000)
    setpos_9.label = 'column1 position'
    node_tree.links.new(prim_6.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 1000)
    vec_10.label = 'column1 position offset'
    vec_10.vector = [30, 30, 0]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    prim_11 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_11.location = (0, 1200)
    prim_11.label = 'column2'
    val_12 = node_tree.nodes.new("ShaderNodeValue")
    val_12.location = (180, 1200)
    val_12.label = 'column2 radius'
    val_12.outputs[0].default_value = 5.05
    val_13 = node_tree.nodes.new("ShaderNodeValue")
    val_13.location = (360, 1200)
    val_13.label = 'column2 depth'
    val_13.outputs[0].default_value = 100
    node_tree.links.new(val_12.outputs["Value"], prim_11.inputs["Radius"])
    node_tree.links.new(val_13.outputs["Value"], prim_11.inputs["Depth"])
    prim_11.inputs["Vertices"].default_value = 32
    setpos_14 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_14.location = (0, 1400)
    setpos_14.label = 'column2 position'
    node_tree.links.new(prim_11.outputs["Mesh"], setpos_14.inputs["Geometry"])
    vec_15 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_15.location = (180, 1400)
    vec_15.label = 'column2 position offset'
    vec_15.vector = [-30, 30, 0]
    node_tree.links.new(vec_15.outputs["Vector"], setpos_14.inputs["Offset"])
    prim_16 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_16.location = (0, 1600)
    prim_16.label = 'column3'
    val_17 = node_tree.nodes.new("ShaderNodeValue")
    val_17.location = (180, 1600)
    val_17.label = 'column3 radius'
    val_17.outputs[0].default_value = 5.05
    val_18 = node_tree.nodes.new("ShaderNodeValue")
    val_18.location = (360, 1600)
    val_18.label = 'column3 depth'
    val_18.outputs[0].default_value = 100
    node_tree.links.new(val_17.outputs["Value"], prim_16.inputs["Radius"])
    node_tree.links.new(val_18.outputs["Value"], prim_16.inputs["Depth"])
    prim_16.inputs["Vertices"].default_value = 32
    setpos_19 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_19.location = (0, 1800)
    setpos_19.label = 'column3 position'
    node_tree.links.new(prim_16.outputs["Mesh"], setpos_19.inputs["Geometry"])
    vec_20 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_20.location = (180, 1800)
    vec_20.label = 'column3 position offset'
    vec_20.vector = [30, -30, 0]
    node_tree.links.new(vec_20.outputs["Vector"], setpos_19.inputs["Offset"])
    prim_21 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_21.location = (0, 2000)
    prim_21.label = 'column4'
    val_22 = node_tree.nodes.new("ShaderNodeValue")
    val_22.location = (180, 2000)
    val_22.label = 'column4 radius'
    val_22.outputs[0].default_value = 5.05
    val_23 = node_tree.nodes.new("ShaderNodeValue")
    val_23.location = (360, 2000)
    val_23.label = 'column4 depth'
    val_23.outputs[0].default_value = 100
    node_tree.links.new(val_22.outputs["Value"], prim_21.inputs["Radius"])
    node_tree.links.new(val_23.outputs["Value"], prim_21.inputs["Depth"])
    prim_21.inputs["Vertices"].default_value = 32
    setpos_24 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_24.location = (0, 2200)
    setpos_24.label = 'column4 position'
    node_tree.links.new(prim_21.outputs["Mesh"], setpos_24.inputs["Geometry"])
    vec_25 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_25.location = (180, 2200)
    vec_25.label = 'column4 position offset'
    vec_25.vector = [-30, -30, 0]
    node_tree.links.new(vec_25.outputs["Vector"], setpos_24.inputs["Offset"])
    bool_26 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_26.location = (0, 2400)
    bool_26.label = 'difference'
    bool_26.operation = "DIFFERENCE"
    bool_26.solver = "EXACT"
    node_tree.links.new(bool_5.outputs["Mesh"], bool_26.inputs[0])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_26.inputs[1])
    node_tree.links.new(setpos_14.outputs["Geometry"], bool_26.inputs[1])
    node_tree.links.new(setpos_19.outputs["Geometry"], bool_26.inputs[1])
    node_tree.links.new(setpos_24.outputs["Geometry"], bool_26.inputs[1])
    xform_27 = node_tree.nodes.new("GeometryNodeTransform")
    xform_27.location = (0, 2600)
    xform_27.label = 'difference rotate'
    node_tree.links.new(bool_26.outputs["Mesh"], xform_27.inputs["Geometry"])
    vec_28 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_28.location = (180, 2600)
    vec_28.label = 'difference rotate rotation'
    vec_28.vector = [0.0, 3.141592653589793, 0.0]
    node_tree.links.new(vec_28.outputs["Vector"], xform_27.inputs["Rotation"])
    xform_29 = node_tree.nodes.new("GeometryNodeTransform")
    xform_29.location = (0, 2800)
    xform_29.label = 'difference rotate translate'
    node_tree.links.new(xform_27.outputs["Geometry"], xform_29.inputs["Geometry"])
    vec_30 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_30.location = (180, 2800)
    vec_30.label = 'difference rotate translate translation'
    vec_30.vector = [0, 0, 170]
    node_tree.links.new(vec_30.outputs["Vector"], xform_29.inputs["Translation"])
    out_31 = node_tree.nodes.new("NodeGroupOutput")
    out_31.location = (0, 3000)
    out_31.label = "output"
    node_tree.links.new(xform_29.outputs[0], out_31.inputs[0])

    return node_tree


# Execute
setup()

