import bpy


def setup(object_name='spacer'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'spacer1'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'spacer1 radius'
    val_2.outputs[0].default_value = 6.925
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'spacer1 depth'
    val_3.outputs[0].default_value = 10
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    prim_4 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_4.location = (0, 400)
    prim_4.label = 'spacer1'
    val_5 = node_tree.nodes.new("ShaderNodeValue")
    val_5.location = (180, 400)
    val_5.label = 'spacer1 radius'
    val_5.outputs[0].default_value = 4.85
    val_6 = node_tree.nodes.new("ShaderNodeValue")
    val_6.location = (360, 400)
    val_6.label = 'spacer1 depth'
    val_6.outputs[0].default_value = 15
    node_tree.links.new(val_5.outputs["Value"], prim_4.inputs["Radius"])
    node_tree.links.new(val_6.outputs["Value"], prim_4.inputs["Depth"])
    prim_4.inputs["Vertices"].default_value = 32
    prim_7 = node_tree.nodes.new("GeometryNodeMeshCube")
    prim_7.location = (0, 600)
    prim_7.label = 'h_spacer_2'
    vec_8 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_8.location = (180, 600)
    vec_8.label = "h_spacer_2 size"
    vec_8.vector = [10, 8, 15]
    node_tree.links.new(vec_8.outputs["Vector"], prim_7.inputs["Size"])
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 800)
    setpos_9.label = 'h_spacer_2 position'
    node_tree.links.new(prim_7.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 800)
    vec_10.label = 'h_spacer_2 position offset'
    vec_10.vector = [5.925, 0, 0]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    bool_11 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_11.location = (0, 1000)
    bool_11.label = 'difference'
    bool_11.operation = "DIFFERENCE"
    bool_11.solver = "EXACT"
    node_tree.links.new(prim_1.outputs["Mesh"], bool_11.inputs[0])
    node_tree.links.new(prim_4.outputs["Mesh"], bool_11.inputs[1])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_11.inputs[1])
    out_12 = node_tree.nodes.new("NodeGroupOutput")
    out_12.location = (0, 1200)
    out_12.label = "output"
    node_tree.links.new(bool_11.outputs[0], out_12.inputs[0])

    return node_tree


# Execute
setup()

