import bpy


def setup(object_name='tol_cyl'):
    """Auto-generated by Tanuki compiler."""
    # Delete existing object if present
    if object_name in bpy.data.objects:
        obj = bpy.data.objects[object_name]
        bpy.data.objects.remove(obj, do_unlink=True)

    # Create base mesh + geometry nodes modifier
    bpy.ops.mesh.primitive_plane_add(size=1, location=(0, 0, 0))
    bpy.context.active_object.name = object_name
    plane = bpy.context.active_object
    modifier = plane.modifiers.new(name="GeometryNodes", type="NODES")
    bpy.ops.node.new_geometry_node_group_assign()
    node_tree = modifier.node_group

    # Clear default nodes
    for node in list(node_tree.nodes):
        node_tree.nodes.remove(node)

    prim_1 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_1.location = (0, 200)
    prim_1.label = 'column1'
    val_2 = node_tree.nodes.new("ShaderNodeValue")
    val_2.location = (180, 200)
    val_2.label = 'column1 radius'
    val_2.outputs[0].default_value = 6.925
    val_3 = node_tree.nodes.new("ShaderNodeValue")
    val_3.location = (360, 200)
    val_3.label = 'column1 depth'
    val_3.outputs[0].default_value = 20
    node_tree.links.new(val_2.outputs["Value"], prim_1.inputs["Radius"])
    node_tree.links.new(val_3.outputs["Value"], prim_1.inputs["Depth"])
    prim_1.inputs["Vertices"].default_value = 32
    setpos_4 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_4.location = (0, 400)
    setpos_4.label = 'column1 position'
    node_tree.links.new(prim_1.outputs["Mesh"], setpos_4.inputs["Geometry"])
    vec_5 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_5.location = (180, 400)
    vec_5.label = 'column1 position offset'
    vec_5.vector = [30, 30, 0]
    node_tree.links.new(vec_5.outputs["Vector"], setpos_4.inputs["Offset"])
    prim_6 = node_tree.nodes.new("GeometryNodeMeshCylinder")
    prim_6.location = (0, 600)
    prim_6.label = 'column1'
    val_7 = node_tree.nodes.new("ShaderNodeValue")
    val_7.location = (180, 600)
    val_7.label = 'column1 radius'
    val_7.outputs[0].default_value = 5.05
    val_8 = node_tree.nodes.new("ShaderNodeValue")
    val_8.location = (360, 600)
    val_8.label = 'column1 depth'
    val_8.outputs[0].default_value = 20
    node_tree.links.new(val_7.outputs["Value"], prim_6.inputs["Radius"])
    node_tree.links.new(val_8.outputs["Value"], prim_6.inputs["Depth"])
    prim_6.inputs["Vertices"].default_value = 32
    setpos_9 = node_tree.nodes.new("GeometryNodeSetPosition")
    setpos_9.location = (0, 800)
    setpos_9.label = 'column1 position'
    node_tree.links.new(prim_6.outputs["Mesh"], setpos_9.inputs["Geometry"])
    vec_10 = node_tree.nodes.new("FunctionNodeInputVector")
    vec_10.location = (180, 800)
    vec_10.label = 'column1 position offset'
    vec_10.vector = [30, 30, 0]
    node_tree.links.new(vec_10.outputs["Vector"], setpos_9.inputs["Offset"])
    bool_11 = node_tree.nodes.new("GeometryNodeMeshBoolean")
    bool_11.location = (0, 1000)
    bool_11.label = 'difference'
    bool_11.operation = "DIFFERENCE"
    bool_11.solver = "EXACT"
    node_tree.links.new(setpos_4.outputs["Geometry"], bool_11.inputs[0])
    node_tree.links.new(setpos_9.outputs["Geometry"], bool_11.inputs[1])
    out_12 = node_tree.nodes.new("NodeGroupOutput")
    out_12.location = (0, 1200)
    out_12.label = "output"
    node_tree.links.new(bool_11.outputs[0], out_12.inputs[0])

    return node_tree


# Execute
setup()

