[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bee"
version = "0.0.1"
authors = [
  { name="Fabian Velosa", email="afvelosas@gmail.com" },
]
description = "Create parametric geometry nodes in Blender using Python."
readme = "README.md"
requires-python = ">=3.11.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/egxn/bee"
Issues = "https://github.com/egxn/bee/issues"

