"""blender.py
─────────────
Export a :class:`~stencil_lab.geometry.Stencil` to a **standalone Blender
script** that builds real curve / mesh geometry.

Why a script and not the Tanuki DSL?  The DSL compiles to *Geometry Nodes* and
its primitives are parametric (circle, line, star, …) — there is no node for an
arbitrary polygon, and pushing thousands of varied halftone primitives through
Geometry Nodes is the wrong tool.  Instead we emit a self-contained ``bpy``
script (the same philosophy as the rest of Tanuki: *models compile to standalone
Blender scripts*), run with::

    blender --background --python stencil.py

What it builds
──────────────
* One **curve object per layer**, named after the channel, each primitive added
  as a spline (dots → polygon circles, polylines → poly splines).
* Optional **2-D fill** (caps) and **Z extrusion** → solid, fabrication-ready
  extruded stencils.
* Per-layer viewport colour from the channel's preview colour.
* Each layer object placed in its own collection so plates stay separable.

Coordinates: image space (top-left origin, y-down) is flipped to Blender's
y-up and multiplied by ``scale`` (units per pixel).  Geometry lies on the XY
plane; extrusion grows along +Z.
"""

from __future__ import annotations

from pathlib import Path

from ..geometry import Dot, Layer, Polyline, Stencil

_HEADER = '''\
"""Generated by tanuki.mori.stencil_lab — Blender stencil builder.

Run:  blender --background --python {fname}
"""
import bpy

EXTRUDE = {extrude!r}   # half-thickness of the solid; 0.0 = flat curves
FILL = {fill!r}         # cap the 2-D curve faces


def _new_curve(name, color):
    cu = bpy.data.curves.new(name, "CURVE")
    cu.dimensions = "2D" if (FILL or EXTRUDE) else "3D"
    if FILL or EXTRUDE:
        cu.fill_mode = "BOTH"
    if EXTRUDE:
        cu.extrude = EXTRUDE
    obj = bpy.data.objects.new(name, cu)
    obj.color = (color[0], color[1], color[2], 1.0)
    coll = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(coll)
    coll.objects.link(obj)
    return cu


def _poly(cu, pts, closed):
    sp = cu.splines.new("POLY")
    sp.points.add(len(pts) - 1)
    for i, (x, y) in enumerate(pts):
        sp.points[i].co = (x, y, 0.0, 1.0)
    sp.use_cyclic_u = closed
'''

_FOOTER = """

if __name__ == "__main__":
    build()
"""


def _t(x: float, y: float, *, h: float, scale: float) -> tuple[float, float]:
    """Image (x, y, top-left) → Blender (x, y, bottom-left), scaled."""
    return (round(x * scale, 4), round((h - y) * scale, 4))


def _circle_points(d: Dot, *, h: float, scale: float, resolution: int) -> list:
    import math
    pts = []
    for i in range(resolution):
        a = 2.0 * math.pi * i / resolution
        pts.append(_t(d.x + d.r * math.cos(a), d.y + d.r * math.sin(a),
                      h=h, scale=scale))
    return pts


def _layer_lines(layer: Layer, *, h: float, scale: float, resolution: int) -> list[str]:
    color = tuple(round(c / 255.0, 4) for c in layer.color)
    lines = [f'    cu = _new_curve({layer.name!r}, {color!r})']
    for prim in layer.primitives:
        if isinstance(prim, Dot):
            pts = _circle_points(prim, h=h, scale=scale, resolution=resolution)
            lines.append(f"    _poly(cu, {pts!r}, True)")
        elif isinstance(prim, Polyline):
            pts = [_t(x, y, h=h, scale=scale) for x, y in prim.points]
            lines.append(f"    _poly(cu, {pts!r}, {prim.closed!r})")
            # holes: extra cyclic splines on the same curve — 2-D fill is even-odd
            for hole in prim.holes:
                hpts = [_t(x, y, h=h, scale=scale) for x, y in hole]
                lines.append(f"    _poly(cu, {hpts!r}, True)")
    return lines


def to_blender_script(
    stencil: Stencil,
    *,
    scale: float = 0.01,
    extrude: float = 0.0,
    fill: bool = True,
    dot_resolution: int = 16,
    fname: str = "stencil.py",
) -> str:
    """Render a stencil to a standalone Blender (``bpy``) script string.

    ``scale``         units (e.g. mm) per source pixel.
    ``extrude``       half-thickness for solid stencils (0 → flat curves).
    ``fill``          cap curve faces (needed for solid plates).
    ``dot_resolution`` polygon segments per halftone dot.
    """
    h = stencil.height
    parts = [_HEADER.format(fname=fname, extrude=float(extrude), fill=bool(fill))]
    parts.append("\ndef build():")
    if not stencil.layers:
        parts.append("    pass")
    for layer in stencil.layers:
        parts.append(f"    # layer: {layer.name} ({len(layer)} primitives)")
        parts.extend(_layer_lines(layer, h=h, scale=scale, resolution=dot_resolution))
    parts.append(_FOOTER)
    return "\n".join(parts)


def write_blender_script(
    stencil: Stencil,
    path: str | Path,
    *,
    scale: float = 0.01,
    extrude: float = 0.0,
    fill: bool = True,
    dot_resolution: int = 16,
) -> Path:
    """Write a stencil to ``path`` as a Blender script, returning the path."""
    path = Path(path)
    src = to_blender_script(
        stencil, scale=scale, extrude=extrude, fill=fill,
        dot_resolution=dot_resolution, fname=path.name,
    )
    path.write_text(src, encoding="utf-8")
    return path
