
def node(type,
        location,
        width,
        height,
        dimensions,
        name,
        label,
        inputs,
        outputs,
        internal_links,
        parent,
        warning_propagation,
        use_custom_color,
        color,
        select,
        show_options,
        show_preview,
        hide,
        mute,
        show_texture,
        bl_idname,
        bl_label,
        bl_description,
        bl_icon,
        bl_static_type,
        bl_width_default,
        bl_width_min,
        bl_width_max,
        bl_height_default,
        bl_height_min,
        bl_height_max,
        ):
  return None